# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secure_update_payment_link_request import SecureUpdatePaymentLinkRequest

class TestSecureUpdatePaymentLinkRequest(unittest.TestCase):
    """SecureUpdatePaymentLinkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureUpdatePaymentLinkRequest:
        """Test SecureUpdatePaymentLinkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureUpdatePaymentLinkRequest`
        """
        model = SecureUpdatePaymentLinkRequest()
        if include_optional:
            return SecureUpdatePaymentLinkRequest(
                amount = 1.337,
                enable_partial_payment = True,
                enable_multiple_payment = True,
                enable_protection = True,
                enable_premium_finance = True,
                expire_in = 56,
                expire_in_unit = 'Seconds',
                settings = openapi_client.models.secure_update_payment_link_request_settings.SecureUpdatePaymentLinkRequest_settings(
                    display_summary = True, 
                    accept_customer_info = True, 
                    remove_header = True, 
                    accept_card = True, 
                    accept_bank_account = True, 
                    save_customer = True, 
                    save_customer_account = True, 
                    additional_details_preference = 'AskShopper', ),
                suppress_technology_fee = True,
                override_technology_fee = 1.337
            )
        else:
            return SecureUpdatePaymentLinkRequest(
        )
        """

    def testSecureUpdatePaymentLinkRequest(self):
        """Test SecureUpdatePaymentLinkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
