# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.outbound_payment_timeline_response_dto_inner import OutboundPaymentTimelineResponseDTOInner

class TestOutboundPaymentTimelineResponseDTOInner(unittest.TestCase):
    """OutboundPaymentTimelineResponseDTOInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutboundPaymentTimelineResponseDTOInner:
        """Test OutboundPaymentTimelineResponseDTOInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutboundPaymentTimelineResponseDTOInner`
        """
        model = OutboundPaymentTimelineResponseDTOInner()
        if include_optional:
            return OutboundPaymentTimelineResponseDTOInner(
                payment_status = 'NA',
                payment_method_status = 'NA',
                modified_on = ''
            )
        else:
            return OutboundPaymentTimelineResponseDTOInner(
        )
        """

    def testOutboundPaymentTimelineResponseDTOInner(self):
        """Test OutboundPaymentTimelineResponseDTOInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
