# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction_payment_response_cc_tender_info import TransactionPaymentResponseCcTenderInfo

class TestTransactionPaymentResponseCcTenderInfo(unittest.TestCase):
    """TransactionPaymentResponseCcTenderInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionPaymentResponseCcTenderInfo:
        """Test TransactionPaymentResponseCcTenderInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionPaymentResponseCcTenderInfo`
        """
        model = TransactionPaymentResponseCcTenderInfo()
        if include_optional:
            return TransactionPaymentResponseCcTenderInfo(
                card_holder_name = '',
                mask_card_number = '',
                card_expiry = '',
                capture_amount = 1.337,
                amount = 1.337,
                bin_number = '',
                tax_amount = 1.337,
                tax_after_discount = 1.337,
                tax_percent = 1.337,
                adjustment_percent_value = 1.337,
                adjustment_fixed_value = 1.337,
                adjustment_amount = 1.337,
                adjustment_display_name = '',
                adjustment_descriptor_message = '',
                payment_adjustment_type = 'CashIncentive',
                pre_auth_code = '',
                mask_account = 1.337,
                account_token = '',
                account_token_message = '',
                create_account_token = True,
                discount_type = 'Fixed',
                discount_percent = 1.337,
                discount_amount = 1.337,
                convenience_amount = 1.337,
                commission_type = 'Fixed',
                commission_value = 1.337
            )
        else:
            return TransactionPaymentResponseCcTenderInfo(
        )
        """

    def testTransactionPaymentResponseCcTenderInfo(self):
        """Test TransactionPaymentResponseCcTenderInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
