# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secure_token_link_update_request import SecureTokenLinkUpdateRequest

class TestSecureTokenLinkUpdateRequest(unittest.TestCase):
    """SecureTokenLinkUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureTokenLinkUpdateRequest:
        """Test SecureTokenLinkUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureTokenLinkUpdateRequest`
        """
        model = SecureTokenLinkUpdateRequest()
        if include_optional:
            return SecureTokenLinkUpdateRequest(
                token_link_id = '',
                expire_in = 56,
                response_type = 'OnScreen',
                expire_in_unit = 'Seconds',
                intent = openapi_client.models.payment_intent_request_intent.PaymentIntentRequest_intent(
                    payment_types = [
                        'CreditCard'
                        ], ),
                call_back_parameters = openapi_client.models.payment_link_response_callback_parameters.PaymentLinkResponse_callbackParameters(
                    callback_success_url = '', 
                    callback_failure_url = '', 
                    access_key = '', 
                    secret_key = '', 
                    reference_no = '', 
                    reference_type = '', 
                    transaction_id = '', 
                    callback_api_url = '', 
                    callback_message = '', 
                    redirection_time = 1.337, )
            )
        else:
            return SecureTokenLinkUpdateRequest(
                token_link_id = '',
                expire_in = 56,
                expire_in_unit = 'Seconds',
                intent = openapi_client.models.payment_intent_request_intent.PaymentIntentRequest_intent(
                    payment_types = [
                        'CreditCard'
                        ], ),
        )
        """

    def testSecureTokenLinkUpdateRequest(self):
        """Test SecureTokenLinkUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
