# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_intent_response import PaymentIntentResponse

class TestPaymentIntentResponse(unittest.TestCase):
    """PaymentIntentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentIntentResponse:
        """Test PaymentIntentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentIntentResponse`
        """
        model = PaymentIntentResponse()
        if include_optional:
            return PaymentIntentResponse(
                payment_token = '',
                amount = 1.337,
                title = '',
                short_description = '',
                payment_description = '',
                invoice_number = '',
                expires_on = '',
                intent = openapi_client.models.payment_intent_response_intent.PaymentIntentResponse_intent(
                    payment_types = [
                        'CreditCard'
                        ], ),
                save_for_future = True,
                enable_premium_finance = True,
                splits = [
                    openapi_client.models.payment_intent_response_splits_inner.PaymentIntentResponse_splits_inner(
                        virtual_account = '', 
                        amount = 1.337, 
                        reference = '', 
                        account_type = '', 
                        charge_indicator = True, )
                    ],
                quote_key = '',
                account_number = '',
                customers = [
                    openapi_client.models.payment_intent_response_customers_inner.PaymentIntentResponse_customers_inner(
                        first_name = '', 
                        last_name = '', 
                        email = '', 
                        phone = '', )
                    ],
                additional_details_preference = 'None',
                selected_customer_fields = '',
                reference_data_list = [
                    openapi_client.models.payment_intent_request_reference_data_list_inner.PaymentIntentRequest_referenceDataList_inner(
                        reference_type = 'QuoteNumber', 
                        reference_number = '', 
                        reference_key = '', )
                    ]
            )
        else:
            return PaymentIntentResponse(
        )
        """

    def testPaymentIntentResponse(self):
        """Test PaymentIntentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
