# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_intent_request import PaymentIntentRequest

class TestPaymentIntentRequest(unittest.TestCase):
    """PaymentIntentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentIntentRequest:
        """Test PaymentIntentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentIntentRequest`
        """
        model = PaymentIntentRequest()
        if include_optional:
            return PaymentIntentRequest(
                save_customer = True,
                customers = [
                    openapi_client.models.payment_intent_request_customers_inner.PaymentIntentRequest_customers_inner(
                        first_name = '', 
                        last_name = '', 
                        email = '', 
                        phone = '', 
                        customer_id = '', )
                    ],
                additional_details_preference = 'None',
                selected_customer_fields = '',
                reference_data_list = [
                    openapi_client.models.payment_intent_request_reference_data_list_inner.PaymentIntentRequest_referenceDataList_inner(
                        reference_type = 'QuoteNumber', 
                        reference_number = '', 
                        reference_key = '', )
                    ],
                reference_type = 'None',
                reference_number = '',
                reference_key = ''
            )
        else:
            return PaymentIntentRequest(
        )
        """

    def testPaymentIntentRequest(self):
        """Test PaymentIntentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
