# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.verify_bank_account_request import VerifyBankAccountRequest

class TestVerifyBankAccountRequest(unittest.TestCase):
    """VerifyBankAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyBankAccountRequest:
        """Test VerifyBankAccountRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyBankAccountRequest`
        """
        model = VerifyBankAccountRequest()
        if include_optional:
            return VerifyBankAccountRequest(
                account_number = '',
                routing_number = '',
                account_holder_name = '',
                statement_display_name = '',
                bank_account_entity = openapi_client.models.verify_bank_account_request_bank_account_entity.VerifyBankAccountRequest_bankAccountEntity(
                    id = '', 
                    type = '', )
            )
        else:
            return VerifyBankAccountRequest(
        )
        """

    def testVerifyBankAccountRequest(self):
        """Test VerifyBankAccountRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
