# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction_payment_response_transaction_entity_split_responses_inner import TransactionPaymentResponseTransactionEntitySplitResponsesInner

class TestTransactionPaymentResponseTransactionEntitySplitResponsesInner(unittest.TestCase):
    """TransactionPaymentResponseTransactionEntitySplitResponsesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionPaymentResponseTransactionEntitySplitResponsesInner:
        """Test TransactionPaymentResponseTransactionEntitySplitResponsesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionPaymentResponseTransactionEntitySplitResponsesInner`
        """
        model = TransactionPaymentResponseTransactionEntitySplitResponsesInner()
        if include_optional:
            return TransactionPaymentResponseTransactionEntitySplitResponsesInner(
                account_alias = '',
                amount = 1.337,
                charge_indicator = True
            )
        else:
            return TransactionPaymentResponseTransactionEntitySplitResponsesInner(
        )
        """

    def testTransactionPaymentResponseTransactionEntitySplitResponsesInner(self):
        """Test TransactionPaymentResponseTransactionEntitySplitResponsesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
