# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_request_dto import PaymentRequestDto

class TestPaymentRequestDto(unittest.TestCase):
    """PaymentRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentRequestDto:
        """Test PaymentRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentRequestDto`
        """
        model = PaymentRequestDto()
        if include_optional:
            return PaymentRequestDto(
                vendor_id = '',
                payment_method = 'Checks',
                amount = 1.337,
                bank_detail = openapi_client.models.bank_detail_dto.BankDetailDto(
                    account_number = '', 
                    routing_number = '', ),
                data = openapi_client.models.payment_request_dto_data.PaymentRequestDto_Data(
                    check_number = 56, 
                    memo = '', 
                    check_date = '', 
                    remittance_data = openapi_client.models.payment_request_dto_data_remittance_data.PaymentRequestDto_Data_remittanceData(
                        headings = [
                            openapi_client.models.heading_dto.HeadingDto(
                                name = '', 
                                type = '', )
                            ], 
                        rows = [
                            [
                                openapi_client.models.row_dto.RowDto(
                                    name = '', 
                                    value = '', 
                                    type = '', )
                                ]
                            ], ), )
            )
        else:
            return PaymentRequestDto(
        )
        """

    def testPaymentRequestDto(self):
        """Test PaymentRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
