# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secure_vendor_update_request_dto import SecureVendorUpdateRequestDTO

class TestSecureVendorUpdateRequestDTO(unittest.TestCase):
    """SecureVendorUpdateRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureVendorUpdateRequestDTO:
        """Test SecureVendorUpdateRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureVendorUpdateRequestDTO`
        """
        model = SecureVendorUpdateRequestDTO()
        if include_optional:
            return SecureVendorUpdateRequestDTO(
                vendor_id = '',
                vendor_name = '',
                vendor_alias_name = '',
                vendor_db_name = '',
                legal_entity_type = 'Corporation',
                payment_method_type = 'Checks',
                notification_type = 'NA',
                vendor_notes = '',
                phone_number = '',
                is_mobile_number = True,
                use_same_as_physical_address = True,
                email = '',
                url = '',
                remittance_address = openapi_client.models.secure_vendor_update_request_dto_remittance_address.SecureVendorUpdateRequestDTO_remittanceAddress(
                    attention = '', 
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = '', 
                    postal_code = '', 
                    address_type = 'NA', 
                    address_source = 'NA', ),
                physical_address = openapi_client.models.secure_vendor_update_request_dto_remittance_address.SecureVendorUpdateRequestDTO_remittanceAddress(
                    attention = '', 
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = '', 
                    postal_code = '', 
                    address_type = 'NA', 
                    address_source = 'NA', )
            )
        else:
            return SecureVendorUpdateRequestDTO(
        )
        """

    def testSecureVendorUpdateRequestDTO(self):
        """Test SecureVendorUpdateRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
