# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_lite_secure_quote_request_insured import PFLiteSecureQuoteRequestInsured

class TestPFLiteSecureQuoteRequestInsured(unittest.TestCase):
    """PFLiteSecureQuoteRequestInsured unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFLiteSecureQuoteRequestInsured:
        """Test PFLiteSecureQuoteRequestInsured
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFLiteSecureQuoteRequestInsured`
        """
        model = PFLiteSecureQuoteRequestInsured()
        if include_optional:
            return PFLiteSecureQuoteRequestInsured(
                id = '',
                first_name = '',
                last_name = '',
                named_insured = '',
                mobile_phone_number = '',
                email_address = '',
                is_cancellation_warning_via_text_enabled = True,
                fax_number = '',
                address = openapi_client.models.pf_lite_secure_quote_request_insured_address.PFLiteSecureQuoteRequest_insured_address(
                    address1 = '', 
                    address2 = '', 
                    city = '', 
                    state = '', 
                    zip = '', 
                    phone_number = '', )
            )
        else:
            return PFLiteSecureQuoteRequestInsured(
                first_name = '',
                last_name = '',
                email_address = '',
                address = openapi_client.models.pf_lite_secure_quote_request_insured_address.PFLiteSecureQuoteRequest_insured_address(
                    address1 = '', 
                    address2 = '', 
                    city = '', 
                    state = '', 
                    zip = '', 
                    phone_number = '', ),
        )
        """

    def testPFLiteSecureQuoteRequestInsured(self):
        """Test PFLiteSecureQuoteRequestInsured"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
