# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_endorsement_response_item_payment_intent_intent import PFEndorsementResponseItemPaymentIntentIntent

class TestPFEndorsementResponseItemPaymentIntentIntent(unittest.TestCase):
    """PFEndorsementResponseItemPaymentIntentIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFEndorsementResponseItemPaymentIntentIntent:
        """Test PFEndorsementResponseItemPaymentIntentIntent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFEndorsementResponseItemPaymentIntentIntent`
        """
        model = PFEndorsementResponseItemPaymentIntentIntent()
        if include_optional:
            return PFEndorsementResponseItemPaymentIntentIntent(
                payment_types = [
                    'NotDefined'
                    ]
            )
        else:
            return PFEndorsementResponseItemPaymentIntentIntent(
        )
        """

    def testPFEndorsementResponseItemPaymentIntentIntent(self):
        """Test PFEndorsementResponseItemPaymentIntentIntent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
