# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_lite_generate_quote_response import PFLiteGenerateQuoteResponse

class TestPFLiteGenerateQuoteResponse(unittest.TestCase):
    """PFLiteGenerateQuoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFLiteGenerateQuoteResponse:
        """Test PFLiteGenerateQuoteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFLiteGenerateQuoteResponse`
        """
        model = PFLiteGenerateQuoteResponse()
        if include_optional:
            return PFLiteGenerateQuoteResponse(
                is_success = True,
                message = '',
                integration_id = '',
                item = openapi_client.models.pf_lite_generate_quote_response_item.PFLiteGenerateQuoteResponse_item(
                    quote_key = 1.337, 
                    premium = 1.337, 
                    down_amount = 1.337, 
                    amount_financed = 1.337, 
                    finance_charge = 1.337, 
                    total_payments = 1.337, 
                    payment_amount = 1.337, 
                    doc_stamp = 1.337, 
                    first_due_date = '', 
                    apr = 1.337, 
                    installments = 56, 
                    batch_id = '', 
                    payments_retained = 1.337, 
                    payment_retained_amount = 1.337, 
                    unsigned_pfa_url = '', 
                    retail_agent_register_login_url = '', 
                    e_sign_result = openapi_client.models.pf_lite_generate_quote_response_item_e_sign_result.PFLiteGenerateQuoteResponse_item_eSignResult(
                        processed = True, 
                        message = '', 
                        batch_id = '', 
                        agent_url = '', 
                        insured_url = '', 
                        e_sign_option = 1.337, ), 
                    errors = '', 
                    pfa = '', 
                    electronic_signature_url = '', )
            )
        else:
            return PFLiteGenerateQuoteResponse(
        )
        """

    def testPFLiteGenerateQuoteResponse(self):
        """Test PFLiteGenerateQuoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
