# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secure_vendor_timeline_request_dto import SecureVendorTimelineRequestDTO

class TestSecureVendorTimelineRequestDTO(unittest.TestCase):
    """SecureVendorTimelineRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureVendorTimelineRequestDTO:
        """Test SecureVendorTimelineRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureVendorTimelineRequestDTO`
        """
        model = SecureVendorTimelineRequestDTO()
        if include_optional:
            return SecureVendorTimelineRequestDTO(
                vendor_id = ''
            )
        else:
            return SecureVendorTimelineRequestDTO(
        )
        """

    def testSecureVendorTimelineRequestDTO(self):
        """Test SecureVendorTimelineRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
