# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secure_vendor_response_dto import SecureVendorResponseDTO

class TestSecureVendorResponseDTO(unittest.TestCase):
    """SecureVendorResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureVendorResponseDTO:
        """Test SecureVendorResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureVendorResponseDTO`
        """
        model = SecureVendorResponseDTO()
        if include_optional:
            return SecureVendorResponseDTO(
                id = '',
                payment_based_id = '',
                legal_entity_type = 'NA',
                merchant_id = '',
                vendor_name = '',
                vendor_alias_name = '',
                vendor_db_name = '',
                payment_method_type = 'Check',
                notification_type = '',
                vendor_notes = '',
                phone_number = '',
                is_mobile_number = True,
                use_same_as_physical_address = True,
                email = '',
                url = '',
                remittance_address = openapi_client.models.secure_vendor_response_dto_remittance_address.SecureVendorResponseDTO_remittanceAddress(
                    attention = '', 
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = '', 
                    postal_code = '', 
                    address_type = 'NA', 
                    address_source = 'NA', ),
                physical_address = openapi_client.models.secure_vendor_response_dto_remittance_address.SecureVendorResponseDTO_remittanceAddress(
                    attention = '', 
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = '', 
                    postal_code = '', 
                    address_type = 'NA', 
                    address_source = 'NA', ),
                vendor_status = 'NA',
                created_by = '',
                modified_by = '',
                created_on = '',
                modified_on = ''
            )
        else:
            return SecureVendorResponseDTO(
        )
        """

    def testSecureVendorResponseDTO(self):
        """Test SecureVendorResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
