# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.secure_ach_validation_api import SecureACHValidationApi


class TestSecureACHValidationApi(unittest.TestCase):
    """SecureACHValidationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecureACHValidationApi()

    def tearDown(self) -> None:
        pass

    def test_utilityapi_secure_verifybankaccounts_post(self) -> None:
        """Test case for utilityapi_secure_verifybankaccounts_post

        This API verifies bank account using secure ACH validation
        """
        pass


if __name__ == '__main__':
    unittest.main()
