# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_link_response_line_items_inner import PaymentLinkResponseLineItemsInner

class TestPaymentLinkResponseLineItemsInner(unittest.TestCase):
    """PaymentLinkResponseLineItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkResponseLineItemsInner:
        """Test PaymentLinkResponseLineItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkResponseLineItemsInner`
        """
        model = PaymentLinkResponseLineItemsInner()
        if include_optional:
            return PaymentLinkResponseLineItemsInner(
                line_item_type = 'External',
                product_id = '',
                description = '',
                quantity = 56,
                rate = 1.337
            )
        else:
            return PaymentLinkResponseLineItemsInner(
        )
        """

    def testPaymentLinkResponseLineItemsInner(self):
        """Test PaymentLinkResponseLineItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
