# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.remittance_data_dto import RemittanceDataDto

class TestRemittanceDataDto(unittest.TestCase):
    """RemittanceDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemittanceDataDto:
        """Test RemittanceDataDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemittanceDataDto`
        """
        model = RemittanceDataDto()
        if include_optional:
            return RemittanceDataDto(
                headings = [
                    openapi_client.models.heading_dto.HeadingDto(
                        name = '', 
                        type = '', )
                    ],
                rows = [
                    [
                        openapi_client.models.row_dto.RowDto(
                            name = '', 
                            value = '', 
                            type = '', )
                        ]
                    ]
            )
        else:
            return RemittanceDataDto(
        )
        """

    def testRemittanceDataDto(self):
        """Test RemittanceDataDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
