# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction_payment_response_ach_tender_info import TransactionPaymentResponseAchTenderInfo

class TestTransactionPaymentResponseAchTenderInfo(unittest.TestCase):
    """TransactionPaymentResponseAchTenderInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionPaymentResponseAchTenderInfo:
        """Test TransactionPaymentResponseAchTenderInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionPaymentResponseAchTenderInfo`
        """
        model = TransactionPaymentResponseAchTenderInfo()
        if include_optional:
            return TransactionPaymentResponseAchTenderInfo(
                bank_name = '',
                routing_number = '',
                account_type = '',
                check_type = '',
                check_number = '',
                name_on_check = '',
                account_holder_name = '',
                account_category = 'Personal',
                capture_amount = 1.337,
                amount = 1.337,
                convenience_amount = 1.337,
                bin_number = '',
                adjustment_percent_value = 1.337,
                adjustment_fixed_value = 1.337,
                adjustment_amount = 1.337,
                adjustment_display_name = '',
                adjustment_descriptor_message = '',
                payment_adjustment_type = 'None',
                pre_auth_code = '',
                mask_account = '',
                account_token = '',
                account_token_message = '',
                create_account_token = True,
                commission_type = 'Fixed',
                commission_value = 1.337,
                commission_fixed_value = 1.337
            )
        else:
            return TransactionPaymentResponseAchTenderInfo(
        )
        """

    def testTransactionPaymentResponseAchTenderInfo(self):
        """Test TransactionPaymentResponseAchTenderInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
