# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.secure_vendor_management_api import SecureVendorManagementApi


class TestSecureVendorManagementApi(unittest.TestCase):
    """SecureVendorManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecureVendorManagementApi()

    def tearDown(self) -> None:
        pass

    def test_vendorapi_secure_merchants_vendors_delete_post(self) -> None:
        """Test case for vendorapi_secure_merchants_vendors_delete_post

        This API deletes vendor into system
        """
        pass

    def test_vendorapi_secure_merchants_vendors_details_post(self) -> None:
        """Test case for vendorapi_secure_merchants_vendors_details_post

        This API gets details of particular vendor
        """
        pass

    def test_vendorapi_secure_merchants_vendors_edit_post(self) -> None:
        """Test case for vendorapi_secure_merchants_vendors_edit_post

        This API Updates the existing vendor
        """
        pass

    def test_vendorapi_secure_merchants_vendors_post(self) -> None:
        """Test case for vendorapi_secure_merchants_vendors_post

        This API creates vendor into system
        """
        pass

    def test_vendorapi_secure_merchants_vendors_search_post(self) -> None:
        """Test case for vendorapi_secure_merchants_vendors_search_post

        This API returns list of all the Vendors of Merchant
        """
        pass

    def test_vendorapi_secure_merchants_vendors_suspend_post(self) -> None:
        """Test case for vendorapi_secure_merchants_vendors_suspend_post

        This API suspends vendor into system
        """
        pass

    def test_vendorapi_secure_merchants_vendors_timeline_post(self) -> None:
        """Test case for vendorapi_secure_merchants_vendors_timeline_post

        This API gets timeline of particular vendor
        """
        pass

    def test_vendorapi_secure_merchants_vendors_unsuspend_post(self) -> None:
        """Test case for vendorapi_secure_merchants_vendors_unsuspend_post

        This API unsuspends vendor into system
        """
        pass


if __name__ == '__main__':
    unittest.main()
