# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_link_response import PaymentLinkResponse

class TestPaymentLinkResponse(unittest.TestCase):
    """PaymentLinkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkResponse:
        """Test PaymentLinkResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkResponse`
        """
        model = PaymentLinkResponse()
        if include_optional:
            return PaymentLinkResponse(
                id = '',
                merchant_id = '',
                title = '',
                payment_link = '',
                short_link = '',
                amount = 1.337,
                payment_description = '',
                expire_by = '',
                expire_on = '',
                apply_payment_adjustments = True,
                enable_partial_payment = True,
                enable_multiple_payment = True,
                payments = [
                    ''
                    ],
                no_of_payment_made = 1.337,
                total_paid_amount = 1.337,
                enable_protection = True,
                protection_mode = '',
                display_receipt = True,
                link_status = 1.337,
                invoice_number = '',
                created_on = '',
                created_by = '',
                modified_on = '',
                modified_by = '',
                short_description = '',
                resonse_type = '',
                callback_parameters = openapi_client.models.payment_link_response_callback_parameters.PaymentLinkResponse_callbackParameters(
                    callback_success_url = '', 
                    callback_failure_url = '', 
                    access_key = '', 
                    secret_key = '', 
                    reference_no = '', 
                    reference_type = '', 
                    transaction_id = '', 
                    callback_api_url = '', 
                    callback_message = '', ),
                customers = [
                    openapi_client.models.payment_link_response_customers_inner.PaymentLinkResponse_customers_inner(
                        first_name = '', 
                        last_name = '', 
                        email = '', 
                        phone = '', 
                        notify_via_sms = True, 
                        notify_via_email = True, )
                    ],
                line_items = [
                    openapi_client.models.payment_link_response_line_items_inner.PaymentLinkResponse_lineItems_inner(
                        line_item_type = 1.337, 
                        product_id = '', 
                        description = '', 
                        quantity = 1.337, 
                        rate = 1.337, )
                    ],
                display_settings = '',
                splits = [
                    openapi_client.models.payment_link_response_splits_inner.PaymentLinkResponse_splits_inner(
                        virtual_account = '', 
                        amount = 1.337, 
                        reference = '', 
                        charge_indicator = True, )
                    ],
                save_for_future = True,
                quote_key = '',
                account_number = '',
                reference_data_list = [
                    openapi_client.models.payment_intent_request_reference_data_list_inner.PaymentIntentRequest_referenceDataList_inner(
                        reference_type = 'QuoteNumber', 
                        reference_number = '', 
                        reference_key = '', )
                    ],
                enable_premium_finance = True,
                is_premium_financier = True,
                pfr = openapi_client.models.payment_link_response_pfr.PaymentLinkResponse_pfr(
                    entity = '', 
                    reference = '', 
                    quote = '', 
                    account_number = '', 
                    payment_type = 'NA', ),
                payment_link_type = 'NA',
                suppress_technology_fee = True,
                override_technology_fee = 1.337,
                is_pf_lite = True,
                is_pay_in_full = True
            )
        else:
            return PaymentLinkResponse(
        )
        """

    def testPaymentLinkResponse(self):
        """Test PaymentLinkResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
