# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction_payment_response_billing_contact import TransactionPaymentResponseBillingContact

class TestTransactionPaymentResponseBillingContact(unittest.TestCase):
    """TransactionPaymentResponseBillingContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionPaymentResponseBillingContact:
        """Test TransactionPaymentResponseBillingContact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionPaymentResponseBillingContact`
        """
        model = TransactionPaymentResponseBillingContact()
        if include_optional:
            return TransactionPaymentResponseBillingContact(
                name = openapi_client.models.transaction_payment_response_billing_contact_name.TransactionPaymentResponse_billingContact_name(
                    title = '', 
                    first_name = '', 
                    middle_name = '', 
                    last_name = '', ),
                company_name = '',
                department = '',
                fax = '',
                phone = '',
                alternate_phone = '',
                mobile = '',
                email = '',
                url = '',
                address = openapi_client.models.transaction_payment_response_billing_contact_address.TransactionPaymentResponse_billingContact_address(
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = 56, 
                    postal_code = '', 
                    time_zone = '', )
            )
        else:
            return TransactionPaymentResponseBillingContact(
        )
        """

    def testTransactionPaymentResponseBillingContact(self):
        """Test TransactionPaymentResponseBillingContact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
