# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import json

from openapi_client import SecureEmbeddedPremiumFinanceEndorsementsApi
from openapi_client.api.secure_embedded_premium_finance_api import SecureEmbeddedPremiumFinanceApi


class TestSecureEmbeddedPremiumFinanceApi(unittest.TestCase):
    """SecureEmbeddedPremiumFinanceApi unit test stubs"""

    def setUp(self) -> None:
        # call configuration file and store as object
        with open('anddone-python-sdk-openapi-codegen/config.json') as f:
            config = json.load(f)
        # store api key, app key, version and origin from config file
        self.api_key = config.api_key
        self.app_key = config.app_key
        self.version = config.version
        self.origin = config.origin

        # store EPF and Endorsement functions as objects
        self.api = SecureEmbeddedPremiumFinanceApi()
        self.endorse = SecureEmbeddedPremiumFinanceEndorsementsApi()

    def tearDown(self) -> None:
        pass

    def test_secure_epf_quotes_generate_post(self) -> None:
        """Test case for secure_epf_quotes_post

        This API will return quote by QuoteKey.

        Done?
        EPF - Generate Quote
        """
        try:
            request = {
                "merchantId": self.app_key,
                "paymentIntentId": "2v6QkOEd",
                "details": {
                    "programIDs": [82262],
                    "couponInvoicePrinted": False,
                    "installments": None,
                    "batchID": "Batch-00543738",
                    "commercial": "NA",
                    "coupon": "NA",
                    "interval": "NA",
                    "downPaymentMethod": "BOTH",
                    "downPaymentPaidBy": "Insured"
                },
                "insured": {
                    "uniqueId": self.app_key,
                    "agentCustomerNumber": "Suyash",
                    "email": "dylan.smith@fmkagency.com",
                    "careOf": "Test",
                    "address": {
                        "name": "Sam",
                        "address1": "1055 Broadway",
                        "address2": "",
                        "city": "Kansas City",
                        "state": "KY",
                        "zip": "64105",
                        "phone": ""
                    }
                },
                "agent": {
                    "uniqueID": self.app_key,
                    "email": "dylan.smith@fmkagency.com",
                    "address": {
                        "name": "Insurance Agency",
                        "address1": "PO Box 486",
                        "address2": "",
                        "city": "Kansas City",
                        "state": "KY",
                        "zip": "64105",
                        "phone": ""
                    }
                },
                "policies": [
                    {
                        "policyID": 2,
                        "premium": 1000,
                        "fee": None,
                        "tax": None,
                        "coverage": "FIRE",
                        "effectiveDate": "2025-05-01T00:00:00",
                        "expirationDate": "2026-05-01T00:00:00",
                        "term": 12,
                        "minimumEarned": None,
                        "minimumLiability": None,
                        "maximumLiability": None,
                        "invoiceNumber": None,
                        "policyFees": None,
                        "company": {
                            "bestNumber": "",
                            "uniqueId": "LIC",
                            "name": "LEXINGTON INSURANCE COMPANY",
                            "address1": "",
                            "address2": "",
                            "city": "Kansas City",
                            "state": "MO",
                            "zip": "",
                            "phone": ""
                        }
                    }
                ]
            }
            result = self.api.secure_epf_quotes_generate_post(self.api_key, self.app_key, self.version, self.origin, request)
            print(result)
        except Exception as e:
            print(e)

    def test_secure_epf_quotes_intent_post(self) -> None:
        """Test case for secure_epf_quotes_intent_post

        This API will return quotes created against a payment intent.

        DONE
        EPF - Get Quote By Payment Intent
        """
        try:
            request = {
                "paymentIntentId": "2v6QkOEd"
            }
            result = self.api.secure_epf_quotes_intent_post(self.api_key, self.app_key, self.version, self.origin, request)
            print(result)
        except Exception as e:
            print(e)

    def test_secure_epf_quotes_post(self) -> None:
        """Test case for secure_epf_quotes_post

        This API will return quote by QuoteKey.

        DONE
        EPF - Get Quote by Quote Key
        """
        try:
            request = {
                "quoteKey": '29650446'
            }
            result = self.api.secure_epf_quotes_post(self.api_key, self.app_key, self.version, self.origin, request)
            print(result)
        except Exception as e:
            print(e)

    def test_secure_retrieve_policy_endorsement_post(self) -> None:
        """Test case for secure_retrieve_policy_endorsement_post

        This API checks the eligibility of a quote for new endorsement.


        EPF - Retrieve Endorsement Eligibility"""
        try:
            request = {
                "accountNumber": "243490",
                "isCommercial": True,
            }
            result = self.endorse.secure_epf_endorsements_post(self.api_key, self.app_key, self.version, self.origin, request)
            print(result)
        except Exception as e:
            print(e)

    def test_secure_update_policy_endorsement_post(self) -> None:
        """Test case for secure_update_policy_endorsement_post

        This API will do return a quote for an existing policy or new policy
        for an existing account


        EPF - Update Policy Endorsement
        """
        try:
            request = {
                "quote": {
                    "merchantReference": "Python test 01",
                    "accountNumber": "243490",
                    "agreementId": "8025326",
                    "policies": [
                        {
                            "policyId": "11746655",
                            "premium": 40000.0,
                            "effectiveDate": "2025-04-30T00:00:00",
                            "expirationDate": "2026-04-30T00:00:00.00",
                            "term": 12,
                            "coverage": "BOP",
                            "company": {
                                "bestNumber": "",
                                "UniqueID": "1733",
                                "name": "Bankers Standard Insurance Co",
                                "careOf": "string",
                                "address1": "string",
                                "address2": "string",
                                "city": "string",
                                "state": "string",
                                "zip": "string",
                                "phone": "string"
                            }
                        }
                    ],
                    "insured": {
                        "AgentCustomerNumber": "Suyash",
                        "Email": "dylan.smith@fmkagency.com",
                        "CareOf": "",
                        "Address": {
                            "Name": "Sam",
                            "Address1": "1055 Broadway",
                            "Address2": "",
                            "City": "Kansas City",
                            "State": "MO",
                            "Zip": "64105",
                            "Phone": ""
                        }
                    }
                }
            }
            result = self.endorse.secure_epf_quote_endorsement_post(self.api_key, self.app_key, self.version, self.origin, request)
            print(result)
        except Exception as e:
            print(e)

    def test_secure_epf_quotes_booking_put(self) -> None:
        """Test case for secure_epf_quotes_booking_put

        This API will update PFA to book a quote.

        EPF - Confirm (Book) Quote
        Done? Needs testing; backend issue
        """
        try:
            request = {
                "quoteKey": 29650588,
                "merchantToken": self.app_key
            }
            result = self.api.secure_epf_quotes_booking_put(self.api_key, self.app_key, self.version, self.origin, request)
            print(result)
        except Exception as e:
            print(e)

    def test_secure_epf_quote_endorsement_booking_put(self) -> None:
        """Test case for secure_epf_quotes_booking_put

        This API will update PFA to book a quote.

        EPF - Confirm (Book) Endorsement
        Done? Needs testing; backend issue
        """
        try:
            request = {
                "quoteKey": 29650588
            }
            result = self.endorse.secure_epf_quote_endorsement_booking_put(self.api_key, self.app_key, self.version, self.origin, request)
            print(result)
        except Exception as e:
            print(e)

    def test_secure_epf_retrievepfa_post(self) -> None:
        """Test case for secure_epf_retrievepfa_post

        This API will return PFA for given quoteKey.

        Broken
        EPF - Retrieve PFA
        """
        try:
            request = {
                "quoteKey": "28274404"
            }
            result = self.api.secure_epf_retrievepfa_post(self.api_key, self.app_key, self.version, self.origin, request)
            print(result)
        except Exception as e:
            print(e)

    def test_secure_merchants_epf_quotes_policy_put(self) -> None:
        """Test case for secure_merchants_epf_quotes_policy_put

        This API is will update the policy number
        Done? Error - Matching Policy not found
        EPF - Update Policy
        """
        try:
            request = {
                "quoteKey": 29650588,
                "premium": 9000,
                "category": "FIRE",
                "newPolicyNumber": "1256"
            }
            result = self.api.secure_epf_merchants_quotes_policy_put(self.api_key, self.app_key, self.version, self.origin, request)
            print(result)
        except Exception as e:
            print(e)

    def test_secure_epf_quotes_captureesign_put(self) -> None:
        """Test case for secure_epf_quotes_captureesign_put

        This API will capture the eSign for a quote

        EPF - Capture eSign
        """
        try:
            request = {
                "merchantToken": self.app_key,
                "quoteKey": "29650588",
                "insuredName": "John",
                "ipAddress": "101.205.12.14",
                "macAddress": "12-34-56-78-9A-BC",
                "captchaToken": "rewgwgwehrtehwytrbwbtyjcxcvnt",
                "actionName": ""
            }

            self.api.secure_epf_quotes_captureesign_put(self.api_key, self.app_key, self.version, self.origin, request)
            print("eSign Captured")
        except Exception as e:
            print(e)


if __name__ == '__main__':
    unittest.main()
