# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_response_dto import PaymentResponseDto

class TestPaymentResponseDto(unittest.TestCase):
    """PaymentResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentResponseDto:
        """Test PaymentResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentResponseDto`
        """
        model = PaymentResponseDto()
        if include_optional:
            return PaymentResponseDto(
                id = '',
                payment_id = '',
                merchant_id = '',
                vendor_id = '',
                payment_status = 'NA',
                payment_method_status = 'NA',
                payment_method = 'Check',
                amount = 1.337,
                data = openapi_client.models.data_dto.DataDto(
                    check_number = 56, 
                    memo = '', 
                    check_date = '', 
                    remittance_data = openapi_client.models.remittance_data_dto.RemittanceDataDto(
                        headings = [
                            openapi_client.models.heading_dto.HeadingDto(
                                name = '', 
                                type = '', )
                            ], 
                        rows = [
                            [
                                openapi_client.models.row_dto.RowDto(
                                    name = '', 
                                    value = '', 
                                    type = '', )
                                ]
                            ], ), ),
                bank_account_details = '',
                vendor_address = ''
            )
        else:
            return PaymentResponseDto(
        )
        """

    def testPaymentResponseDto(self):
        """Test PaymentResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
