# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vendor_response_dto import VendorResponseDTO

class TestVendorResponseDTO(unittest.TestCase):
    """VendorResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VendorResponseDTO:
        """Test VendorResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VendorResponseDTO`
        """
        model = VendorResponseDTO()
        if include_optional:
            return VendorResponseDTO(
                id = '',
                payment_based_id = '',
                legal_entity_type = 'NA',
                merchant_id = '',
                vendor_name = '',
                vendor_alias_name = '',
                vendor_db_name = '',
                payment_method_type = 'Check',
                notification_type = 'NA',
                vendor_notes = '',
                phone_number = '',
                is_mobile_number = True,
                email = '',
                url = '',
                vendor_status = 'NA',
                use_same_as_physical_address = True,
                remittance_address = openapi_client.models.vendor_response_dto_remittance_address.VendorResponseDTO_remittanceAddress(
                    vendor_id = '', 
                    attention = '', 
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = '', 
                    postal_code = '', 
                    address_type = 'NA', 
                    address_source = 'NA', 
                    verification_status = 'NA', ),
                physical_address = openapi_client.models.vendor_response_dto_remittance_address.VendorResponseDTO_remittanceAddress(
                    vendor_id = '', 
                    attention = '', 
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    state = '', 
                    country = '', 
                    postal_code = '', 
                    address_type = 'NA', 
                    address_source = 'NA', 
                    verification_status = 'NA', ),
                verification_results = [
                    openapi_client.models.vendor_response_dto_verification_results_inner.VendorResponseDTO_verificationResults_inner(
                        vendor_id = '', 
                        verification_type = 'NA', 
                        verification_status = 'NA', 
                        verification_reason = '', 
                        verified_on = '', )
                    ],
                created_by = '',
                modified_by = '',
                created_on = '',
                modified_on = '',
                approved_date = '',
                template = openapi_client.models.vendor_response_dto_template.VendorResponseDTO_template(
                    id = '', 
                    template_name = '', 
                    template_json = '', 
                    is_system_default = True, )
            )
        else:
            return VendorResponseDTO(
        )
        """

    def testVendorResponseDTO(self):
        """Test VendorResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
