# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secure_vendor_status_request_dto import SecureVendorStatusRequestDTO

class TestSecureVendorStatusRequestDTO(unittest.TestCase):
    """SecureVendorStatusRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureVendorStatusRequestDTO:
        """Test SecureVendorStatusRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureVendorStatusRequestDTO`
        """
        model = SecureVendorStatusRequestDTO()
        if include_optional:
            return SecureVendorStatusRequestDTO(
                vendor_id = '',
                reason = ''
            )
        else:
            return SecureVendorStatusRequestDTO(
        )
        """

    def testSecureVendorStatusRequestDTO(self):
        """Test SecureVendorStatusRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
