# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_batch_details_response import PaymentBatchDetailsResponse

class TestPaymentBatchDetailsResponse(unittest.TestCase):
    """PaymentBatchDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentBatchDetailsResponse:
        """Test PaymentBatchDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentBatchDetailsResponse`
        """
        model = PaymentBatchDetailsResponse()
        if include_optional:
            return PaymentBatchDetailsResponse(
                batch_id = '',
                merchant_id = '',
                batch_status = '',
                process_methods = '',
                processor_name = '',
                is_default = True,
                executed_on_demand = True,
                execution_time = '',
                completion_time = '',
                created_on = '',
                created_by = '',
                modified_on = '',
                modified_by = '',
                capture_count = 1.337,
                capture_amount = 1.337,
                voided_count = 1.337,
                voided_amount = 1.337,
                total_live_amount = 1.337,
                refunded_count = 1.337,
                refunded_amount = 1.337,
                chargeback_count = 1.337,
                chargeback_amount = 1.337,
                transaction_details = [
                    openapi_client.models.payment_batch_details_response_transaction_details_inner.PaymentBatchDetailsResponse_transactionDetails_inner(
                        transaction_id = '', 
                        transaction_status = '', 
                        transaction_date_time = '', 
                        transaction_amount = 1.337, )
                    ]
            )
        else:
            return PaymentBatchDetailsResponse(
        )
        """

    def testPaymentBatchDetailsResponse(self):
        """Test PaymentBatchDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
