# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import datetime
from dateutil import relativedelta
import unittest
import json

import pytest

import openapi_client
from openapi_client.api.secure_premium_finance_lite_api import SecurePremiumFinanceLiteApi


class TestSecurePremiumFinanceLiteApi(unittest.TestCase):
    """SecurePremiumFinanceLiteApi unit test stubs"""

    def setUp(self) -> None:
        # call configuration file and store as object
        with open('anddone-python-sdk-openapi-codegen/config.json') as f:
            config = json.load(f)
        # store api key, app key, version and origin from config file
        self.api_key = config.api_key
        self.app_key = config.app_key
        self.version = config.version
        self.origin = config.origin

        # store secure token links api functions as an object
        self.api = openapi_client.api.secure_premium_finance_lite_api.SecurePremiumFinanceLiteApi()  # noqa: E501
        self.timestamp = datetime.date.today() + relativedelta.relativedelta(months=1)
        self.timestamp = self.timestamp.strftime('%m-%d-%Y')
        self.next_month = datetime.date.today() + relativedelta.relativedelta(months=2)
        self.next_month = self.next_month.strftime('%m-%d-%Y')

    def tearDown(self) -> None:
        pass

    @pytest.mark.order(1)
    def test_secure_epflite_quotes_generate_post(self) -> None:
        """Test case for secure_epflite_quotes_generate_post

        This API is used to generate the quote from the provider.
        PFL - Generate Premium Finance Lite Quote
        """
        try:
            request = {
                "merchantId": self.app_key,
                "merchant": {
                    "contactName": "John Doe",
                    "contactPhone": "0123456789"
                },
                "insured": {
                    "firstName": "Jane",
                    "lastName": "Smith",
                    "mobilePhoneNumber": None,
                    "faxNumber": None,
                    "emailAddress": "test@email.com",
                    "isCancellationWarningViaTextEnabled": False,
                    "address": {
                        "address1": "1055",
                        "address2": "Broadway Blvd",
                        "city": "Anchorage",
                        "state": "AK",
                        "zip": "64105",
                        "phoneNumber": None
                    }
                },
                "program": {
                    "programId": 82262,
                    "loanType": "Personal"
                },
                "policies": [
                    {
                        "premium": 20000,
                        # "effectiveDate": self.timestamp + " 00:00:00",
                        # "expirationDate": self.next_month + " 00:00:00",
                        "effectiveDate": "05-01-2025 00:00:00",
                        "expirationDate": "05-01-2026 00:00:00",
                        "coverageType": "FIRE",
                        "cancelDays": "Item20",
                        "additionalFees": 0,
                        "minimumEarnedPercent": 0,
                        "policyNumber": "21128675311",
                        "carrier": {
                            "name": "OCCIDENTAL FIRE & CASUALTY CO OF NO",
                            "bestNumber": "5555551234",
                            "uniqueId": "23248"
                        }
                    }
                ]
            }

            response = self.api.secure_epflite_quotes_generate_post(self.api_key, self.app_key, self.version, self.origin, request)
            print(response)
            # pytest.quote_key = response['quote_key']
        except Exception as e:
            print(e)

    @pytest.mark.order(2)
    def test_secure_epflite_quotes_paymentlinks_post(self) -> None:
        """Test case for secure_epflite_quotes_paymentlinks_post

        This API is used to generate the quote from the provider.
        """
        try:
            # quote_key = pytest.quote_key
            request = {
                # "quoteKey": quote_key,
                "quoteKey": "29649161",
                "isPayInFull": False,
                "title": "FirstPayment",
                "paymentDescription": "FirstPayment",
                "expireIn": 3,
                "expireInUnit": "Days",
                "customers": [
                    {
                        "firstName": "Testing",
                        "lastName": "Tester",
                        "email": "Testing.Tester@email.com",
                        "phone": "1234567890",
                        "Address": {
                            "address1": "1055",
                            "address2": "Broadway Blvd",
                            "city": "Anchorage",
                            "state": "AK",
                            "zip": "64105",
                            "phoneNumber": None
                        },
                        "notifyViaSMS": False,
                        "notifyViaEmail": False
                    }
                ],
                "callbackParameters": {
                    "callbackApiUrl": "htttp://yahoo.com",
                    "callbackMessage": "this is test message"
                },
                "referenceDataList": [
                    {
                        "referenceType": "PolicyNumber",
                        "referenceNumber": "pol123",
                        "referenceKey": None
                    }
                ],
                "settings": {
                    "selectedCustomerFields": "First Name,Last Name,Email,Phone",
                    "additionalDetailsPreference": "ManualEnter",
                    "intent": {
                        "paymentTypes": [
                            "ACH",
                            "CreditCard",
                            "DebitCard"
                        ]
                    }
                }
            }
            response = self.api.secure_epflite_quotes_paymentlinks_post(self.api_key, self.app_key, self.version,
                                                                    self.origin, request)
            print(response)
            # pytest.payment_link_id = response['payment_link_id']
        except Exception as e:
            print(e)

    @pytest.mark.order(3)
    def test_secure_epflite_quotes_link_post(self) -> None:
        """Test case for secure_epflite_quotes_link_post

        This API will return quotes created againsts a payment link.
        PFL - Generate Premium Finance Lite Payment Link
        """

        try:
            # payment_link_id = pytest.payment_link_id
            request = {
                "merchantToken": self.app_key,
                # "payment_link_id": payment_link_id
                'paymentLinkId': 'qx7rbEGv'
            }
            response = self.api.secure_epflite_quotes_link_post(self.api_key, self.app_key, self.version,
                                                                self.origin, request)
            print(response)
        except Exception as e:
            print(e)


if __name__ == '__main__':
    unittest.main()
