# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_list_response_dto import PaymentListResponseDTO

class TestPaymentListResponseDTO(unittest.TestCase):
    """PaymentListResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentListResponseDTO:
        """Test PaymentListResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentListResponseDTO`
        """
        model = PaymentListResponseDTO()
        if include_optional:
            return PaymentListResponseDTO(
                id = '',
                merchant_id = '',
                merchant_dba_name = '',
                payment_method_type = 'Checks',
                payment_based_id = '',
                vendor_id = '',
                vendor_name = '',
                payment_id = '',
                payment_method_status = 'NA',
                requested_date = '',
                amount = ''
            )
        else:
            return PaymentListResponseDTO(
        )
        """

    def testPaymentListResponseDTO(self):
        """Test PaymentListResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
