# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_endorsement_request_quote_policies_inner_policy_fee_inner import PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner

class TestPFEndorsementRequestQuotePoliciesInnerPolicyFeeInner(unittest.TestCase):
    """PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner:
        """Test PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner`
        """
        model = PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner()
        if include_optional:
            return PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner(
                fee_name = '',
                fee_amount = 1.337
            )
        else:
            return PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner(
        )
        """

    def testPFEndorsementRequestQuotePoliciesInnerPolicyFeeInner(self):
        """Test PFEndorsementRequestQuotePoliciesInnerPolicyFeeInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
