# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secure_update_payment_link_request_settings_intent import SecureUpdatePaymentLinkRequestSettingsIntent

class TestSecureUpdatePaymentLinkRequestSettingsIntent(unittest.TestCase):
    """SecureUpdatePaymentLinkRequestSettingsIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureUpdatePaymentLinkRequestSettingsIntent:
        """Test SecureUpdatePaymentLinkRequestSettingsIntent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureUpdatePaymentLinkRequestSettingsIntent`
        """
        model = SecureUpdatePaymentLinkRequestSettingsIntent()
        if include_optional:
            return SecureUpdatePaymentLinkRequestSettingsIntent(
                payment_types = [
                    'ACH'
                    ]
            )
        else:
            return SecureUpdatePaymentLinkRequestSettingsIntent(
        )
        """

    def testSecureUpdatePaymentLinkRequestSettingsIntent(self):
        """Test SecureUpdatePaymentLinkRequestSettingsIntent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
