# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auto_pay_enrollment_response import AutoPayEnrollmentResponse

class TestAutoPayEnrollmentResponse(unittest.TestCase):
    """AutoPayEnrollmentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoPayEnrollmentResponse:
        """Test AutoPayEnrollmentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoPayEnrollmentResponse`
        """
        model = AutoPayEnrollmentResponse()
        if include_optional:
            return AutoPayEnrollmentResponse(
                message = '',
                is_success = True,
                integration_id = ''
            )
        else:
            return AutoPayEnrollmentResponse(
        )
        """

    def testAutoPayEnrollmentResponse(self):
        """Test AutoPayEnrollmentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
