# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import json

from openapi_client.api.secure_embedded_premium_finance_endorsements_api import SecureEmbeddedPremiumFinanceEndorsementsApi


class TestSecureEmbeddedPremiumFinanceEndorsementsApi(unittest.TestCase):
    """SecureEmbeddedPremiumFinanceEndorsementsApi unit test stubs"""

    def setUp(self) -> None:
        # call configuration file and store as object
        with open('anddone-python-sdk-openapi-codegen/config.json') as f:
            config = json.load(f)
        # store api key, app key, version and origin from config file
        self.api_key = config.api_key
        self.app_key = config.app_key
        self.version = config.version
        self.origin = config.origin

        # store EPF and Endorsement functions as objects
        self.api = SecureEmbeddedPremiumFinanceEndorsementsApi()

    def tearDown(self) -> None:
        pass

    def test_secure_epf_endorsements_post(self) -> None:
        """Test case for secure_epf_endorsements_post

        This API will do a check of eligibility of account
        """
        pass

    def test_secure_epf_quote_endorsement_booking_put(self) -> None:
        """Test case for secure_epf_quote_endorsement_booking_put

        This API will update PFA to book a endorsement quote.
        """
        pass

    def test_secure_epf_quote_endorsement_post(self) -> None:
        """Test case for secure_epf_quote_endorsement_post

        This API will do return a quote for an existing policy or new policy for an existing account
        """
        pass


if __name__ == '__main__':
    unittest.main()
