# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import json

from openapi_client.api.secure_token_management_api import SecureTokenManagementApi


class TestSecureTokenManagementApi(unittest.TestCase):
    """SecureTokenManagementApi unit test stubs"""

    def setUp(self) -> None:
        # call configuration file and store as object
        with open('anddone-python-sdk-openapi-codegen/config.json') as f:
            config = json.load(f)
        # store api key, app key, version and origin from config file
        self.api_key = config.api_key
        self.app_key = config.app_key
        self.version = config.version
        self.origin = config.origin

        # store secure token management api functions as an object
        self.api = SecureTokenManagementApi()

    def tearDown(self) -> None:
        pass

    def test_secure_tokens_activations_delete(self) -> None:
        """Test case for secure_tokens_activations_delete

        This API is used for deactivating merchant token securely
        """
        try:
            request = {
                "token": "MJEPEG3VZEVXYPRZ"
            }

            self.api.secure_tokens_activations_delete(self.api_key,
                                                      self.app_key,
                                                      self.version,
                                                      self.origin,
                                                      request)
            print("Account token deleted successfully")
        except Exception as e:
            print(e)

    def test_secure_tokens_details_post(self) -> None:
        """Test case for secure_tokens_details_post

        This API is used for retrieving token details securely
        """
        try:
            request = {
                "tokenLinkId": "DxnX3wjd"
            }

            response = self.api.secure_tokens_details_post(self.api_key,
                                                           self.app_key,
                                                           self.version,
                                                           self.origin,
                                                           request)
            print(response)
        except Exception as e:
            print(e)


if __name__ == '__main__':
    unittest.main()
