# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_link_request import PaymentLinkRequest

class TestPaymentLinkRequest(unittest.TestCase):
    """PaymentLinkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkRequest:
        """Test PaymentLinkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkRequest`
        """
        model = PaymentLinkRequest()
        if include_optional:
            return PaymentLinkRequest(
                merchant_id = '',
                title = '',
                amount = 1.337,
                payment_description = '',
                customers = [
                    openapi_client.models.payment_link_response_customers_inner.PaymentLinkResponse_customers_inner(
                        first_name = '', 
                        last_name = '', 
                        email = '', 
                        phone = '', 
                        notify_via_sms = True, 
                        notify_via_email = True, 
                        created_on = '', 
                        accounts = [
                            openapi_client.models.payment_link_response_customers_inner_accounts_inner.PaymentLinkResponse_customers_inner_accounts_inner(
                                id = '', 
                                channel_type = 'ACH', 
                                card_number = '', 
                                card_type = '', 
                                account_token = '', 
                                account_number = '', 
                                bank_name = '', 
                                is_checking_account = True, 
                                is_expired = True, 
                                created_on = '', 
                                created_by = '', 
                                modified_on = '', 
                                modified_by = '', )
                            ], 
                        address = openapi_client.models.transaction_payment_response_billing_contact_address.TransactionPaymentResponse_billingContact_address(
                            address_line1 = '', 
                            address_line2 = '', 
                            city = '', 
                            state = '', 
                            country = 56, 
                            postal_code = '', 
                            time_zone = '', ), )
                    ],
                invoice_number = '',
                expire_by = 1.337,
                expire_in = 56,
                expire_in_unit = 'Seconds',
                expire_on = '',
                line_items = [
                    openapi_client.models.payment_link_response_line_items_inner.PaymentLinkResponse_lineItems_inner(
                        line_item_type = 'External', 
                        product_id = '', 
                        description = '', 
                        quantity = 56, 
                        rate = 1.337, )
                    ],
                short_description = '',
                response_type = 'OnScreen',
                callback_parameters = openapi_client.models.payment_link_response_callback_parameters.PaymentLinkResponse_callbackParameters(
                    callback_success_url = '', 
                    callback_failure_url = '', 
                    access_key = '', 
                    secret_key = '', 
                    reference_no = '', 
                    reference_type = '', 
                    transaction_id = '', 
                    callback_api_url = '', 
                    callback_message = '', 
                    redirection_time = 1.337, ),
                settings = openapi_client.models.payment_link_request_settings.PaymentLinkRequest_settings(
                    selected_customer_fields = '', 
                    additional_details_preference = 'None', 
                    display_summary = True, 
                    accept_customer_info = True, 
                    remove_header = True, 
                    accept_card = True, 
                    accept_bank_account = True, 
                    save_customer = True, 
                    save_customer_account = True, 
                    intent = openapi_client.models.payment_link_request_settings_intent.PaymentLinkRequest_settings_intent(
                        payment_types = [
                            'ACH'
                            ], ), ),
                payment_link_type = 'NA',
                save_for_future = True,
                splits = [
                    openapi_client.models.payment_intent_request_splits_inner.PaymentIntentRequest_splits_inner(
                        virtual_account = '', 
                        amount = 1.337, 
                        reference = '', 
                        account_type = '', 
                        charge_indicator = True, )
                    ],
                quote_key = '',
                account_number = '',
                reference_type = 'None',
                reference_number = '',
                reference_key = '',
                reference_data_list = [
                    openapi_client.models.payment_link_response_reference_data_list_inner.PaymentLinkResponse_referenceDataList_inner(
                        reference_type = 'QuoteId', 
                        reference_number = '', 
                        reference_key = '', )
                    ],
                enable_premium_finance = True,
                suppress_technology_fee = True,
                override_technology_fee = 1.337,
                platform_settlement_status = 'NotDefined',
                is_pay_in_full = True,
                is_premium_financier = True,
                pfr = openapi_client.models.payment_intent_request_pfr.PaymentIntentRequest_pfr(
                    entity = '', 
                    reference = '', 
                    quote = '', 
                    account_number = '', 
                    payment_type = 'NA', ),
                pf_type = 'PF'
            )
        else:
            return PaymentLinkRequest(
                merchant_id = '',
                title = '',
                amount = 1.337,
                expire_in = 56,
                expire_in_unit = 'Seconds',
                settings = openapi_client.models.payment_link_request_settings.PaymentLinkRequest_settings(
                    selected_customer_fields = '', 
                    additional_details_preference = 'None', 
                    display_summary = True, 
                    accept_customer_info = True, 
                    remove_header = True, 
                    accept_card = True, 
                    accept_bank_account = True, 
                    save_customer = True, 
                    save_customer_account = True, 
                    intent = openapi_client.models.payment_link_request_settings_intent.PaymentLinkRequest_settings_intent(
                        payment_types = [
                            'ACH'
                            ], ), ),
                reference_data_list = [
                    openapi_client.models.payment_link_response_reference_data_list_inner.PaymentLinkResponse_referenceDataList_inner(
                        reference_type = 'QuoteId', 
                        reference_number = '', 
                        reference_key = '', )
                    ],
        )
        """

    def testPaymentLinkRequest(self):
        """Test PaymentLinkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
