# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.secure_autopay_enrollment_api import SecureAutopayEnrollmentApi


class TestSecureAutopayEnrollmentApi(unittest.TestCase):
    """SecureAutopayEnrollmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecureAutopayEnrollmentApi()

    def tearDown(self) -> None:
        pass

    def test_secure_autopayenrollment_post(self) -> None:
        """Test case for secure_autopayenrollment_post

        This API is used for Autopay Enrollment.
        """
        pass


if __name__ == '__main__':
    unittest.main()
