# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.quote_request_agent_address import QuoteRequestAgentAddress

class TestQuoteRequestAgentAddress(unittest.TestCase):
    """QuoteRequestAgentAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuoteRequestAgentAddress:
        """Test QuoteRequestAgentAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuoteRequestAgentAddress`
        """
        model = QuoteRequestAgentAddress()
        if include_optional:
            return QuoteRequestAgentAddress(
                name = '',
                address1 = '',
                address2 = '',
                city = '',
                state = '',
                zip = '',
                phone = ''
            )
        else:
            return QuoteRequestAgentAddress(
                name = '',
                address1 = '',
        )
        """

    def testQuoteRequestAgentAddress(self):
        """Test QuoteRequestAgentAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
