# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secure_verify_bank_account_request_dto import SecureVerifyBankAccountRequestDTO

class TestSecureVerifyBankAccountRequestDTO(unittest.TestCase):
    """SecureVerifyBankAccountRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecureVerifyBankAccountRequestDTO:
        """Test SecureVerifyBankAccountRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecureVerifyBankAccountRequestDTO`
        """
        model = SecureVerifyBankAccountRequestDTO()
        if include_optional:
            return SecureVerifyBankAccountRequestDTO(
                verification_entity_id = '',
                account_number = '',
                routing_number = '',
                account_holder_name = '',
                explicit_verification = True
            )
        else:
            return SecureVerifyBankAccountRequestDTO(
                account_number = '',
                routing_number = '',
        )
        """

    def testSecureVerifyBankAccountRequestDTO(self):
        """Test SecureVerifyBankAccountRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
