# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.token_link_response_data_inner_intent import TokenLinkResponseDataInnerIntent

class TestTokenLinkResponseDataInnerIntent(unittest.TestCase):
    """TokenLinkResponseDataInnerIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenLinkResponseDataInnerIntent:
        """Test TokenLinkResponseDataInnerIntent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenLinkResponseDataInnerIntent`
        """
        model = TokenLinkResponseDataInnerIntent()
        if include_optional:
            return TokenLinkResponseDataInnerIntent(
                payment_types = 'NotDefined'
            )
        else:
            return TokenLinkResponseDataInnerIntent(
        )
        """

    def testTokenLinkResponseDataInnerIntent(self):
        """Test TokenLinkResponseDataInnerIntent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
