# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.outbound_payment_image_response_dto import OutboundPaymentImageResponseDTO

class TestOutboundPaymentImageResponseDTO(unittest.TestCase):
    """OutboundPaymentImageResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutboundPaymentImageResponseDTO:
        """Test OutboundPaymentImageResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutboundPaymentImageResponseDTO`
        """
        model = OutboundPaymentImageResponseDTO()
        if include_optional:
            return OutboundPaymentImageResponseDTO(
                image = ''
            )
        else:
            return OutboundPaymentImageResponseDTO(
        )
        """

    def testOutboundPaymentImageResponseDTO(self):
        """Test OutboundPaymentImageResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
