# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.quote_request_policies_inner_ga import QuoteRequestPoliciesInnerGa

class TestQuoteRequestPoliciesInnerGa(unittest.TestCase):
    """QuoteRequestPoliciesInnerGa unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuoteRequestPoliciesInnerGa:
        """Test QuoteRequestPoliciesInnerGa
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuoteRequestPoliciesInnerGa`
        """
        model = QuoteRequestPoliciesInnerGa()
        if include_optional:
            return QuoteRequestPoliciesInnerGa(
                unique_id = '',
                name = '',
                care_of = '',
                is_validation_required = True,
                address = openapi_client.models.quote_request_insured_address.QuoteRequest_insured_address(
                    name = '', 
                    address1 = '', 
                    address2 = '', 
                    city = '', 
                    state = '', 
                    zip = '', 
                    phone = '', )
            )
        else:
            return QuoteRequestPoliciesInnerGa(
        )
        """

    def testQuoteRequestPoliciesInnerGa(self):
        """Test QuoteRequestPoliciesInnerGa"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
