# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_lite_payment_link_request_callback_parameters import PFLitePaymentLinkRequestCallbackParameters

class TestPFLitePaymentLinkRequestCallbackParameters(unittest.TestCase):
    """PFLitePaymentLinkRequestCallbackParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFLitePaymentLinkRequestCallbackParameters:
        """Test PFLitePaymentLinkRequestCallbackParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFLitePaymentLinkRequestCallbackParameters`
        """
        model = PFLitePaymentLinkRequestCallbackParameters()
        if include_optional:
            return PFLitePaymentLinkRequestCallbackParameters(
                callback_api_url = '',
                callback_message = '',
                access_key = '',
                secret_key = '',
                reference_no = '',
                reference_type = '',
                transaction_id = '',
                redirection_time = 1.337
            )
        else:
            return PFLitePaymentLinkRequestCallbackParameters(
        )
        """

    def testPFLitePaymentLinkRequestCallbackParameters(self):
        """Test PFLitePaymentLinkRequestCallbackParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
