# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_transaction_entity_response_data_inner import MerchantTransactionEntityResponseDataInner

class TestMerchantTransactionEntityResponseDataInner(unittest.TestCase):
    """MerchantTransactionEntityResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantTransactionEntityResponseDataInner:
        """Test MerchantTransactionEntityResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantTransactionEntityResponseDataInner`
        """
        model = MerchantTransactionEntityResponseDataInner()
        if include_optional:
            return MerchantTransactionEntityResponseDataInner(
                transaction_id = '',
                merchant_id = '',
                ip_address = '',
                transaction_date = '',
                operation_type = 'Sale',
                channel_type = 'NotDefined',
                process_method = 'NotDefined',
                is_debit = True,
                reference_transaction_id = '',
                reference_customer_id = '',
                recurring_id = '',
                batch_id = 1.337,
                transaction_status = 'Created',
                settlement_date = '',
                auth_code = '',
                card_number = '',
                account_number = '',
                bin_number = '',
                cheque_number = '',
                routing_number = '',
                name_on_check_or_card = '',
                account_holder_name = '',
                account_category = 'Unknown',
                training_mode = True,
                amount = 1.337,
                convenience_amount = 1.337,
                capture_amount = 1.337,
                card_type = '',
                created_on = '',
                created_by = '',
                modified_on = '',
                modified_by = '',
                customer_name = '',
                partner_id = '',
                partner_name = '',
                order_id = '',
                invoice_id = '',
                payment_link_id = '',
                reference_no = '',
                processor_name = '',
                processor_display_name = '',
                verification2_code = '',
                transaction_origin = 'Terminal',
                previous_transaction_status = 'Created',
                trace_number = '',
                merchant_reference = '',
                additiona_fields = '',
                adjustment_value = 1.337,
                adjustment_fixed_value = 1.337,
                adjustment_amount = 1.337,
                adjustment_display_name = '',
                adjustment_descriptor_message = '',
                payment_adjustment_type = 'None',
                commission_type = 'Fixed',
                commission_value = 1.337,
                commission_fixed_value = 1.337,
                account_token = '',
                payment_type = 'None',
                payment_category = 'None',
                refund_reason = '',
                refund_detail = '',
                full_account_number = '',
                refund_type = 'NA',
                suppress_technology_fee = True
            )
        else:
            return MerchantTransactionEntityResponseDataInner(
        )
        """

    def testMerchantTransactionEntityResponseDataInner(self):
        """Test MerchantTransactionEntityResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
