# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import json

import openapi_client
from openapi_client.api.secure_reports_api import SecureReportsApi


class TestSecureReportsApi(unittest.TestCase):
    """SecureReportsApi unit test stubs"""

    def setUp(self) -> None:
        # call configuration file and store as object
        with open('anddone-python-sdk-openapi-codegen/config.json') as f:
            config = json.load(f)
        # store api key, app key, version and origin from config file
        self.api_key = config.api_key
        self.app_key = config.app_key
        self.version = config.version
        self.origin = config.origin

        # store secure payments api functions as an object
        self.api = SecureReportsApi()

    def tearDown(self) -> None:
        pass

    def test_secure_reports_downloads_post(self) -> None:
        """Test case for secure_reports_downloads_post

        This API will add system report.
        """
        try:
            request = {
                "reportId": "report_payment_settlement_2024_10_02",
                "date": "10-02-2024",
            }

            self.api.secure_reports_downloads_post(self.api_key,
                                                   self.app_key,
                                                   self.version,
                                                   self.origin,
                                                   request)
            # print(response)
            # self.assertIsInstance(response, AdminTransactionEntityResponse)
        except Exception as e:
            print(e)


if __name__ == '__main__':
    unittest.main()
