# coding: utf-8

"""
    Secure API

    Secure API's

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import json
import pytest

import openapi_client
from openapi_client import SecurePaymentDetailsRequest, PaymentRequest
# from openapi_client import AdminTransactionEntityResponse, TransactionResponse
from openapi_client.api.secure_payments_api import SecurePaymentsApi


class TestSecurePaymentsApi(unittest.TestCase):
    """SecurePaymentsApi unit test stubs"""

    def setUp(self) -> None:
        # call configuration file and store as object
        with open('anddone-python-sdk-openapi-codegen/config.json') as f:
            config = json.load(f)
        # store api key, app key, version and origin from config file
        self.api_key = config.api_key
        self.app_key = config.app_key
        self.version = config.version
        self.origin = config.origin

        # store secure payments api functions as an object
        self.api = openapi_client.api.secure_payments_api.SecurePaymentsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    # def test_secure_payments_export_post(self) -> None:
    #     """Test case for secure_payments_export_post
    #
    #     This API gets Secure payment by search criteria for the merchant.
    #     """
    #     pass

    @pytest.mark.order(1)
    def test_secure_payments_post(self) -> None:
        """Test case for secure_payments_post

        This API posts new Secure payment request for the merchant.
        SP - Create Secure Payments
        """
        request = {
                "paymentReference": "PMT-543216785",
                "type": "OpenPayment",
                "tenderInfo": {
                    "amount": 178,
                    "cardHolderName": "John Doe",
                    "cardType": "VISA",
                    "cardNumber": "4000620000000007",
                    "cardExpiry": "0330",
                    "cvDataStatus": "AV",
                    "cvv": "737",
                    "removeDiscounting": False
                },
                "transactionCode": "Web",
                "channelType": "CreditCard",
                "billingcontact": {
                    "phone": "8003213388",
                    "name": {
                        "firstname": "John",
                        "lastname": "Doe"
                    },
                    "address": {
                        "addressLine1": "30",
                        "addressLine2": "Memorial Drive",
                        "city": "Avon ",
                        "state": "NY",
                        "country": 1,
                        "postalCode": "12701"
                    }
                }
            }


        response = self.api.secure_payments_post(self.api_key, self.app_key,
                                                 self.version, self.origin,
                                                 request)
        # # self.assertIsInstance(response, TransactionResponse)
        # pytest.transaction_id = response['transactionId']
        print(response)
        # # assert response message matches expected
        # expected = request['paymentReference']
        # actual = response['referenceNo']
        # self.assertEqual(actual, expected)

    @pytest.mark.order(2)
    def test_secure_payments_search_post(self) -> None:
        """Test case for secure_payments_search_post

        This API gets Secure payment by search criteria for the merchant.
        SP - Search Secure Payments
        """
        try:
            response = self.api.secure_payments_search_post(self.api_key,
                                                            self.app_key,
                                                            self.version,
                                                            self.origin,
                                                            start_date="06-01-2024",
                                                            end_date="04-25-2025",
                                                            start_row=0,
                                                            page_size=10)
            print(response)
            # self.assertIsInstance(response, AdminTransactionEntityResponse)
        except Exception as e:
            print(e)

    @pytest.mark.order(3)
    def test_secure_paymentsdetails_post(self) -> None:
        """Test case for secure_paymentsdetails_post

        This API is used for getting details of Payments
        TM - Get Payment Details by Transaction ID
        """
        try:
            # transaction_id = pytest.transaction_id
            transaction_id = 'c5ffedc0-d42e-439e-9efa-526528937e98'
            request = SecurePaymentDetailsRequest.from_dict(
                {"id": transaction_id,
                "type": "OpenPayment"}
            )

            response = self.api.secure_paymentsdetails_post(self.api_key,
                                                            self.app_key,
                                                            self.version,
                                                            self.origin,
                                                            request)
            # print(response)
            # actual = response.transaction_id
            # expected = pytest.transaction_id
            # self.assertEqual(actual, expected)
            print(response)
        except Exception as e:
            print(e)

        """TM - Get Payment Details by Payment Token"""

        try:
            request = SecurePaymentDetailsRequest.from_dict(
                {
                    "paymentToken": "MxakMkkd",
                    "type": "PaymentIntent"
                }
            )

            response = self.api.secure_paymentsdetails_post(self.api_key,
                                                            self.app_key,
                                                            self.version,
                                                            self.origin,
                                                            request)
            print(response)
        except Exception as e:
            print(e)

    @pytest.mark.order(4)
    def test_secure_payments_export_post(self) -> None:
        """Test case for secure_payments_search_post

        This API gets Secure payment by search criteria for the merchant.
        SP - Search Secure Payments
        """
        try:
            self.api.secure_payments_export_post(self.api_key,
                                                 self.app_key,
                                                 self.version,
                                                 self.origin,
                                                 start_date="06-01-2024",
                                                 end_date="04-25-2025",
                                                 start_row=0,
                                                 page_size=10)

            # self.assertIsInstance(response, AdminTransactionEntityResponse)
            print("Payments Exported Successfully")
        except Exception as e:
            print(e)

    @pytest.mark.order(5)
    def test_secure_cancellations_post(self) -> None:
        """Test case for secure_cancellations_post

        This API is used for voiding a transaction
        Can - Cancel Transaction
        """
        # try:
        #     transaction_id = pytest.transaction_id
        #     request = {
        #         "transactionId": transaction_id,
        #         "voidReason": "Duplicate transaction"
        #     }
        #
        #     response = self.api.secure_cancellations_post(self.api_key,
        #                                                     self.app_key,
        #                                                     self.origin,
        #                                                     self.version,
        #                                                     request)
        #     print(response)
        #     # actual = response.transaction_id
        #     # expected = pytest.transaction_id
        #     # self.assertEqual(actual, expected)
        # except Exception as e:
        #     print(e)


def suite():
    test_suite = unittest.TestSuite()
    test_suite.addTest(TestSecurePaymentsApi('test_secure_payments_post'))
    return test_suite


if __name__ == '__main__':
    unittest.TextTestRunner().run(suite())
