# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pf_lite_secure_quote_request_agent_address import PFLiteSecureQuoteRequestAgentAddress

class TestPFLiteSecureQuoteRequestAgentAddress(unittest.TestCase):
    """PFLiteSecureQuoteRequestAgentAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PFLiteSecureQuoteRequestAgentAddress:
        """Test PFLiteSecureQuoteRequestAgentAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PFLiteSecureQuoteRequestAgentAddress`
        """
        model = PFLiteSecureQuoteRequestAgentAddress()
        if include_optional:
            return PFLiteSecureQuoteRequestAgentAddress(
                name = '',
                address1 = '',
                address2 = '',
                city = '',
                state = '',
                zip = '',
                phone = ''
            )
        else:
            return PFLiteSecureQuoteRequestAgentAddress(
        )
        """

    def testPFLiteSecureQuoteRequestAgentAddress(self):
        """Test PFLiteSecureQuoteRequestAgentAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
