# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.token_link_response import TokenLinkResponse

class TestTokenLinkResponse(unittest.TestCase):
    """TokenLinkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenLinkResponse:
        """Test TokenLinkResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenLinkResponse`
        """
        model = TokenLinkResponse()
        if include_optional:
            return TokenLinkResponse(
                total_row_count = 1.337,
                data = [
                    openapi_client.models.token_link_response_data_inner.TokenLinkResponse_data_inner(
                        merchant_id = '', 
                        token_link_id = '', 
                        title = '', 
                        url = '', 
                        expire_on = '', 
                        created_on = '', 
                        modified_on = '', 
                        created_by = '', 
                        modified_by = '', 
                        token_link_status = 'NA', 
                        response_type = 'OnScreen', 
                        call_back_parameters = openapi_client.models.payment_link_response_callback_parameters.PaymentLinkResponse_callbackParameters(
                            callback_success_url = '', 
                            callback_failure_url = '', 
                            access_key = '', 
                            secret_key = '', 
                            reference_no = '', 
                            reference_type = '', 
                            transaction_id = '', 
                            callback_api_url = '', 
                            callback_message = '', 
                            redirection_time = 1.337, ), 
                        intent = openapi_client.models.secure_token_link_response_intent.SecureTokenLinkResponse_intent(
                            payment_types = 'NotDefined', ), 
                        customers = [
                            openapi_client.models.secure_token_link_response_customers_inner.SecureTokenLinkResponse_customers_inner(
                                first_name = '', 
                                last_name = '', 
                                email = '', 
                                phone = '', 
                                address = openapi_client.models.transaction_payment_response_billing_contact_address.TransactionPaymentResponse_billingContact_address(
                                    address_line1 = '', 
                                    address_line2 = '', 
                                    city = '', 
                                    state = '', 
                                    country = 56, 
                                    postal_code = '', 
                                    time_zone = '', ), )
                            ], )
                    ]
            )
        else:
            return TokenLinkResponse(
        )
        """

    def testTokenLinkResponse(self):
        """Test TokenLinkResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
