# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vendor_response_dto_remittance_address import VendorResponseDTORemittanceAddress

class TestVendorResponseDTORemittanceAddress(unittest.TestCase):
    """VendorResponseDTORemittanceAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VendorResponseDTORemittanceAddress:
        """Test VendorResponseDTORemittanceAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VendorResponseDTORemittanceAddress`
        """
        model = VendorResponseDTORemittanceAddress()
        if include_optional:
            return VendorResponseDTORemittanceAddress(
                vendor_id = '',
                attention = '',
                address_line1 = '',
                address_line2 = '',
                city = '',
                state = '',
                country = '',
                postal_code = '',
                address_type = 'NA',
                address_source = 'NA',
                verification_status = 'NA'
            )
        else:
            return VendorResponseDTORemittanceAddress(
        )
        """

    def testVendorResponseDTORemittanceAddress(self):
        """Test VendorResponseDTORemittanceAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
