# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.secure_orum_api import SecureOrumApi


class TestSecureOrumApi(unittest.TestCase):
    """SecureOrumApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecureOrumApi()

    def tearDown(self) -> None:
        pass

    def test_secure_bankaccounts_details_post(self) -> None:
        """Test case for secure_bankaccounts_details_post

        This API will request for verified bank account.
        """
        pass

    def test_secure_bankaccounts_verify_post(self) -> None:
        """Test case for secure_bankaccounts_verify_post

        This API will request for account verification.
        """
        pass


if __name__ == '__main__':
    unittest.main()
