# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_request_tender_info import PaymentRequestTenderInfo

class TestPaymentRequestTenderInfo(unittest.TestCase):
    """PaymentRequestTenderInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentRequestTenderInfo:
        """Test PaymentRequestTenderInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentRequestTenderInfo`
        """
        model = PaymentRequestTenderInfo()
        if include_optional:
            return PaymentRequestTenderInfo(
                bank_name = '',
                account_number = '',
                routing_number = '',
                account_type = '',
                check_number = '',
                account_category = 'Unknown',
                account_holder_name = '',
                name_on_check = '',
                card_holder_name = '',
                card_type = '',
                card_number = '',
                card_expiry = '',
                cvv = '',
                cv_data_status = '',
                track_data = '',
                remove_discounting = True,
                suppress_commission = True,
                amount = 1.337,
                convenience_amount = 1.337,
                pre_auth_code = '',
                create_account_token = True,
                account_token = ''
            )
        else:
            return PaymentRequestTenderInfo(
        )
        """

    def testPaymentRequestTenderInfo(self):
        """Test PaymentRequestTenderInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
