# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AutoPayEnrollmentRequest(BaseModel):
    """
    AutoPayEnrollmentRequest
    """ # noqa: E501
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    quote_key: StrictStr = Field(alias="Quote Key")
    payment_intent_id: StrictStr = Field(alias="paymentIntentId")
    email_address: StrictStr = Field(alias="emailAddress")
    process_method: StrictStr = Field(alias="processMethod")
    credit_card_token: Optional[StrictStr] = Field(default=None, alias="creditCardToken")
    channel_type: Optional[StrictStr] = Field(default=None, alias="channelType")
    cardholder_name: Optional[StrictStr] = Field(default=None, alias="cardholderName")
    adyen_psp: Optional[StrictStr] = Field(default=None, alias="adyenPSP")
    account_owner_name: Optional[StrictStr] = Field(default=None, alias="accountOwnerName")
    bank_routing_number: Optional[StrictStr] = Field(default=None, alias="bankRoutingNumber")
    bank_account_number: Optional[StrictStr] = Field(default=None, alias="bankAccountNumber")
    account_type: Optional[StrictStr] = Field(default=None, alias="accountType")
    __properties: ClassVar[List[str]] = ["merchantId", "Quote Key", "paymentIntentId", "emailAddress", "processMethod", "creditCardToken", "channelType", "cardholderName", "adyenPSP", "accountOwnerName", "bankRoutingNumber", "bankAccountNumber", "accountType"]

    @field_validator('process_method')
    def process_method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['NotDefined', 'ACH', 'CardNotPresent']):
            raise ValueError("must be one of enum values ('NotDefined', 'ACH', 'CardNotPresent')")
        return value

    @field_validator('channel_type')
    def channel_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NotDefined', 'ACH', 'CreditCard', 'DebitCard', 'RTP']):
            raise ValueError("must be one of enum values ('NotDefined', 'ACH', 'CreditCard', 'DebitCard', 'RTP')")
        return value

    @field_validator('account_type')
    def account_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['checking', 'savings']):
            raise ValueError("must be one of enum values ('checking', 'savings')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AutoPayEnrollmentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AutoPayEnrollmentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchantId": obj.get("merchantId"),
            "Quote Key": obj.get("Quote Key"),
            "paymentIntentId": obj.get("paymentIntentId"),
            "emailAddress": obj.get("emailAddress"),
            "processMethod": obj.get("processMethod"),
            "creditCardToken": obj.get("creditCardToken"),
            "channelType": obj.get("channelType"),
            "cardholderName": obj.get("cardholderName"),
            "adyenPSP": obj.get("adyenPSP"),
            "accountOwnerName": obj.get("accountOwnerName"),
            "bankRoutingNumber": obj.get("bankRoutingNumber"),
            "bankAccountNumber": obj.get("bankAccountNumber"),
            "accountType": obj.get("accountType")
        })
        return _obj


