# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.vendor_response_dto_remittance_address import VendorResponseDTORemittanceAddress
from openapi_client.models.vendor_response_dto_template import VendorResponseDTOTemplate
from openapi_client.models.vendor_response_dto_verification_results_inner import VendorResponseDTOVerificationResultsInner
from typing import Optional, Set
from typing_extensions import Self

class PageVendorResponseDTODataInner(BaseModel):
    """
    PageVendorResponseDTODataInner
    """ # noqa: E501
    id: Optional[StrictStr] = None
    payment_based_id: Optional[StrictStr] = Field(default=None, alias="paymentBasedId")
    legal_entity_type: Optional[StrictStr] = Field(default=None, alias="legalEntityType")
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    vendor_name: Optional[StrictStr] = Field(default=None, alias="vendorName")
    vendor_alias_name: Optional[StrictStr] = Field(default=None, alias="vendorAliasName")
    vendor_db_name: Optional[StrictStr] = Field(default=None, alias="vendorDbName")
    payment_method_type: Optional[StrictStr] = Field(default=None, alias="paymentMethodType")
    notification_type: Optional[StrictStr] = Field(default=None, alias="notificationType")
    vendor_notes: Optional[StrictStr] = Field(default=None, alias="vendorNotes")
    phone_number: Optional[StrictStr] = Field(default=None, alias="phoneNumber")
    is_mobile_number: Optional[StrictBool] = Field(default=None, alias="isMobileNumber")
    email: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    vendor_status: Optional[StrictStr] = Field(default=None, alias="vendorStatus")
    use_same_as_physical_address: Optional[StrictBool] = Field(default=None, alias="useSameAsPhysicalAddress")
    physical_address: Optional[VendorResponseDTORemittanceAddress] = Field(default=None, alias="physicalAddress")
    remittance_address: Optional[VendorResponseDTORemittanceAddress] = Field(default=None, alias="remittanceAddress")
    verification_results: Optional[List[VendorResponseDTOVerificationResultsInner]] = Field(default=None, alias="verificationResults")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    modified_by: Optional[StrictStr] = Field(default=None, alias="modifiedBy")
    created_on: Optional[StrictStr] = Field(default=None, alias="createdOn")
    modified_on: Optional[StrictStr] = Field(default=None, alias="modifiedOn")
    approved_date: Optional[StrictStr] = Field(default=None, alias="approvedDate")
    template: Optional[VendorResponseDTOTemplate] = None
    __properties: ClassVar[List[str]] = ["id", "paymentBasedId", "legalEntityType", "merchantId", "vendorName", "vendorAliasName", "vendorDbName", "paymentMethodType", "notificationType", "vendorNotes", "phoneNumber", "isMobileNumber", "email", "url", "vendorStatus", "useSameAsPhysicalAddress", "physicalAddress", "remittanceAddress", "verificationResults", "createdBy", "modifiedBy", "createdOn", "modifiedOn", "approvedDate", "template"]

    @field_validator('legal_entity_type')
    def legal_entity_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'Corporation', 'LimitedLiabilityCompany', 'LimitedLiabilityPartnership', 'LimitedPartnership', 'Partnership', 'Individual']):
            raise ValueError("must be one of enum values ('NA', 'Corporation', 'LimitedLiabilityCompany', 'LimitedLiabilityPartnership', 'LimitedPartnership', 'Partnership', 'Individual')")
        return value

    @field_validator('payment_method_type')
    def payment_method_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Check']):
            raise ValueError("must be one of enum values ('Check')")
        return value

    @field_validator('vendor_status')
    def vendor_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'Reviewing', 'Approved', 'Denied', 'Suspended', 'Deleted']):
            raise ValueError("must be one of enum values ('NA', 'Reviewing', 'Approved', 'Denied', 'Suspended', 'Deleted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PageVendorResponseDTODataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of physical_address
        if self.physical_address:
            _dict['physicalAddress'] = self.physical_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of remittance_address
        if self.remittance_address:
            _dict['remittanceAddress'] = self.remittance_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in verification_results (list)
        _items = []
        if self.verification_results:
            for _item_verification_results in self.verification_results:
                if _item_verification_results:
                    _items.append(_item_verification_results.to_dict())
            _dict['verificationResults'] = _items
        # override the default output from pydantic by calling `to_dict()` of template
        if self.template:
            _dict['template'] = self.template.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PageVendorResponseDTODataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "paymentBasedId": obj.get("paymentBasedId"),
            "legalEntityType": obj.get("legalEntityType"),
            "merchantId": obj.get("merchantId"),
            "vendorName": obj.get("vendorName"),
            "vendorAliasName": obj.get("vendorAliasName"),
            "vendorDbName": obj.get("vendorDbName"),
            "paymentMethodType": obj.get("paymentMethodType"),
            "notificationType": obj.get("notificationType"),
            "vendorNotes": obj.get("vendorNotes"),
            "phoneNumber": obj.get("phoneNumber"),
            "isMobileNumber": obj.get("isMobileNumber"),
            "email": obj.get("email"),
            "url": obj.get("url"),
            "vendorStatus": obj.get("vendorStatus"),
            "useSameAsPhysicalAddress": obj.get("useSameAsPhysicalAddress"),
            "physicalAddress": VendorResponseDTORemittanceAddress.from_dict(obj["physicalAddress"]) if obj.get("physicalAddress") is not None else None,
            "remittanceAddress": VendorResponseDTORemittanceAddress.from_dict(obj["remittanceAddress"]) if obj.get("remittanceAddress") is not None else None,
            "verificationResults": [VendorResponseDTOVerificationResultsInner.from_dict(_item) for _item in obj["verificationResults"]] if obj.get("verificationResults") is not None else None,
            "createdBy": obj.get("createdBy"),
            "modifiedBy": obj.get("modifiedBy"),
            "createdOn": obj.get("createdOn"),
            "modifiedOn": obj.get("modifiedOn"),
            "approvedDate": obj.get("approvedDate"),
            "template": VendorResponseDTOTemplate.from_dict(obj["template"]) if obj.get("template") is not None else None
        })
        return _obj


