# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PaymentListResponseDTO(BaseModel):
    """
    PaymentListResponseDTO
    """ # noqa: E501
    id: Optional[StrictStr] = None
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    merchant_dba_name: Optional[StrictStr] = Field(default=None, alias="merchantDBAName")
    payment_method_type: Optional[StrictStr] = Field(default=None, alias="paymentMethodType")
    payment_based_id: Optional[StrictStr] = Field(default=None, alias="paymentBasedId")
    vendor_id: Optional[StrictStr] = Field(default=None, alias="vendorId")
    vendor_name: Optional[StrictStr] = Field(default=None, alias="vendorName")
    payment_id: Optional[StrictStr] = Field(default=None, alias="paymentId")
    payment_method_status: Optional[StrictStr] = Field(default=None, alias="paymentMethodStatus")
    requested_date: Optional[StrictStr] = Field(default=None, alias="requestedDate")
    amount: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "merchantId", "merchantDBAName", "paymentMethodType", "paymentBasedId", "vendorId", "vendorName", "paymentId", "paymentMethodStatus", "requestedDate", "amount"]

    @field_validator('payment_method_type')
    def payment_method_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Check']):
            raise ValueError("must be one of enum values ('Check')")
        return value

    @field_validator('payment_method_status')
    def payment_method_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'Accepted', 'PrintQueued', 'Printed', 'Mailed', 'Delivered', 'Pdf', 'Cancelled', 'Warning', 'Failed', 'Returned']):
            raise ValueError("must be one of enum values ('NA', 'Accepted', 'PrintQueued', 'Printed', 'Mailed', 'Delivered', 'Pdf', 'Cancelled', 'Warning', 'Failed', 'Returned')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentListResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentListResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "merchantId": obj.get("merchantId"),
            "merchantDBAName": obj.get("merchantDBAName"),
            "paymentMethodType": obj.get("paymentMethodType"),
            "paymentBasedId": obj.get("paymentBasedId"),
            "vendorId": obj.get("vendorId"),
            "vendorName": obj.get("vendorName"),
            "paymentId": obj.get("paymentId"),
            "paymentMethodStatus": obj.get("paymentMethodStatus"),
            "requestedDate": obj.get("requestedDate"),
            "amount": obj.get("amount")
        })
        return _obj


