# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.payment_intent_request_pfr import PaymentIntentRequestPfr
from openapi_client.models.payment_intent_request_splits_inner import PaymentIntentRequestSplitsInner
from openapi_client.models.payment_link_request_reference_data_list_inner import PaymentLinkRequestReferenceDataListInner
from openapi_client.models.payment_link_request_settings import PaymentLinkRequestSettings
from openapi_client.models.payment_link_response_callback_parameters import PaymentLinkResponseCallbackParameters
from openapi_client.models.payment_link_response_customers_inner import PaymentLinkResponseCustomersInner
from openapi_client.models.payment_link_response_line_items_inner import PaymentLinkResponseLineItemsInner
from typing import Optional, Set
from typing_extensions import Self

class PaymentLinkRequest(BaseModel):
    """
    PaymentLinkRequest
    """ # noqa: E501
    merchant_id: StrictStr = Field(alias="merchantId")
    title: StrictStr
    amount: Union[StrictFloat, StrictInt]
    payment_description: StrictStr = Field(alias="paymentDescription")
    customers: Optional[List[PaymentLinkResponseCustomersInner]] = None
    invoice_number: Optional[StrictStr] = Field(default=None, alias="invoiceNumber")
    expire_by: Optional[StrictInt] = Field(default=None, alias="expireBy")
    expire_in: StrictInt = Field(alias="expireIn")
    expire_in_unit: StrictStr = Field(alias="expireInUnit")
    expire_on: Optional[StrictStr] = Field(default=None, alias="expireOn")
    line_items: Optional[List[PaymentLinkResponseLineItemsInner]] = Field(default=None, alias="lineItems")
    short_description: Optional[StrictStr] = Field(default=None, alias="shortDescription")
    response_type: Optional[StrictStr] = Field(default=None, alias="responseType")
    callback_parameters: Optional[PaymentLinkResponseCallbackParameters] = Field(default=None, alias="callbackParameters")
    settings: PaymentLinkRequestSettings
    payment_link_type: Optional[StrictStr] = Field(default=None, alias="paymentLinkType")
    save_for_future: Optional[StrictBool] = Field(default=None, alias="saveForFuture")
    splits: Optional[List[PaymentIntentRequestSplitsInner]] = None
    quote_key: Optional[StrictStr] = Field(default=None, alias="quoteKey")
    account_number: Optional[StrictStr] = Field(default=None, alias="accountNumber")
    reference_type: Optional[StrictStr] = Field(default=None, alias="referenceType")
    reference_number: Optional[StrictStr] = Field(default=None, alias="referenceNumber")
    reference_key: Optional[StrictStr] = Field(default=None, alias="referenceKey")
    reference_data_list: List[PaymentLinkRequestReferenceDataListInner] = Field(alias="referenceDataList")
    enable_premium_finance: Optional[StrictBool] = Field(default=None, alias="enablePremiumFinance")
    suppress_technology_fee: Optional[StrictBool] = Field(default=None, alias="suppressTechnologyFee")
    override_technology_fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="overrideTechnologyFee")
    platform_settlement_status: Optional[StrictStr] = Field(default=None, alias="platformSettlementStatus")
    is_pay_in_full: Optional[StrictBool] = Field(default=None, alias="isPayInFull")
    is_premium_financier: Optional[StrictBool] = Field(default=None, alias="isPremiumFinancier")
    pfr: Optional[PaymentIntentRequestPfr] = None
    pf_type: Optional[StrictStr] = Field(default=None, alias="pfType")
    __properties: ClassVar[List[str]] = ["merchantId", "title", "amount", "paymentDescription", "customers", "invoiceNumber", "expireBy", "expireIn", "expireInUnit", "expireOn", "lineItems", "shortDescription", "responseType", "callbackParameters", "settings", "paymentLinkType", "saveForFuture", "splits", "quoteKey", "accountNumber", "referenceType", "referenceNumber", "referenceKey", "referenceDataList", "enablePremiumFinance", "suppressTechnologyFee", "overrideTechnologyFee", "platformSettlementStatus", "isPayInFull", "isPremiumFinancier", "pfr", "pfType"]

    @field_validator('expire_in_unit')
    def expire_in_unit_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Seconds', 'Minutes', 'Hours', 'Days', 'Weeks']):
            raise ValueError("must be one of enum values ('Seconds', 'Minutes', 'Hours', 'Days', 'Weeks')")
        return value

    @field_validator('response_type')
    def response_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['OnScreen', 'CallBack']):
            raise ValueError("must be one of enum values ('OnScreen', 'CallBack')")
        return value

    @field_validator('payment_link_type')
    def payment_link_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'PaymentLink', 'PaymentIntent', 'TokenLink', 'Invoice']):
            raise ValueError("must be one of enum values ('NA', 'PaymentLink', 'PaymentIntent', 'TokenLink', 'Invoice')")
        return value

    @field_validator('reference_type')
    def reference_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'QuoteNumber', 'AccountNumber', 'PolicyNumber', 'InvoiceNumber', 'OtherNumber']):
            raise ValueError("must be one of enum values ('None', 'QuoteNumber', 'AccountNumber', 'PolicyNumber', 'InvoiceNumber', 'OtherNumber')")
        return value

    @field_validator('platform_settlement_status')
    def platform_settlement_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NotDefined', 'Pending', 'Settled']):
            raise ValueError("must be one of enum values ('NotDefined', 'Pending', 'Settled')")
        return value

    @field_validator('pf_type')
    def pf_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PF', 'PFLite']):
            raise ValueError("must be one of enum values ('PF', 'PFLite')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentLinkRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in customers (list)
        _items = []
        if self.customers:
            for _item_customers in self.customers:
                if _item_customers:
                    _items.append(_item_customers.to_dict())
            _dict['customers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in line_items (list)
        _items = []
        if self.line_items:
            for _item_line_items in self.line_items:
                if _item_line_items:
                    _items.append(_item_line_items.to_dict())
            _dict['lineItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of callback_parameters
        if self.callback_parameters:
            _dict['callbackParameters'] = self.callback_parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in splits (list)
        _items = []
        if self.splits:
            for _item_splits in self.splits:
                if _item_splits:
                    _items.append(_item_splits.to_dict())
            _dict['splits'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reference_data_list (list)
        _items = []
        if self.reference_data_list:
            for _item_reference_data_list in self.reference_data_list:
                if _item_reference_data_list:
                    _items.append(_item_reference_data_list.to_dict())
            _dict['referenceDataList'] = _items
        # override the default output from pydantic by calling `to_dict()` of pfr
        if self.pfr:
            _dict['pfr'] = self.pfr.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentLinkRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchantId": obj.get("merchantId"),
            "title": obj.get("title"),
            "amount": obj.get("amount"),
            "paymentDescription": obj.get("paymentDescription"),
            "customers": [PaymentLinkResponseCustomersInner.from_dict(_item) for _item in obj["customers"]] if obj.get("customers") is not None else None,
            "invoiceNumber": obj.get("invoiceNumber"),
            "expireBy": obj.get("expireBy"),
            "expireIn": obj.get("expireIn"),
            "expireInUnit": obj.get("expireInUnit"),
            "expireOn": obj.get("expireOn"),
            "lineItems": [PaymentLinkResponseLineItemsInner.from_dict(_item) for _item in obj["lineItems"]] if obj.get("lineItems") is not None else None,
            "shortDescription": obj.get("shortDescription"),
            "responseType": obj.get("responseType"),
            "callbackParameters": PaymentLinkResponseCallbackParameters.from_dict(obj["callbackParameters"]) if obj.get("callbackParameters") is not None else None,
            "settings": PaymentLinkRequestSettings.from_dict(obj["settings"]) if obj.get("settings") is not None else None,
            "paymentLinkType": obj.get("paymentLinkType"),
            "saveForFuture": obj.get("saveForFuture"),
            "splits": [PaymentIntentRequestSplitsInner.from_dict(_item) for _item in obj["splits"]] if obj.get("splits") is not None else None,
            "quoteKey": obj.get("quoteKey"),
            "accountNumber": obj.get("accountNumber"),
            "referenceType": obj.get("referenceType"),
            "referenceNumber": obj.get("referenceNumber"),
            "referenceKey": obj.get("referenceKey"),
            "referenceDataList": [PaymentLinkRequestReferenceDataListInner.from_dict(_item) for _item in obj["referenceDataList"]] if obj.get("referenceDataList") is not None else None,
            "enablePremiumFinance": obj.get("enablePremiumFinance"),
            "suppressTechnologyFee": obj.get("suppressTechnologyFee"),
            "overrideTechnologyFee": obj.get("overrideTechnologyFee"),
            "platformSettlementStatus": obj.get("platformSettlementStatus"),
            "isPayInFull": obj.get("isPayInFull"),
            "isPremiumFinancier": obj.get("isPremiumFinancier"),
            "pfr": PaymentIntentRequestPfr.from_dict(obj["pfr"]) if obj.get("pfr") is not None else None,
            "pfType": obj.get("pfType")
        })
        return _obj


