# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.heading_dto import HeadingDto
from openapi_client.models.row_dto import RowDto
from typing import Optional, Set
from typing_extensions import Self

class PaymentRequestDtoDataRemittanceData(BaseModel):
    """
    PaymentRequestDtoDataRemittanceData
    """ # noqa: E501
    headings: Optional[List[HeadingDto]] = None
    rows: Optional[List[List[RowDto]]] = None
    __properties: ClassVar[List[str]] = ["headings", "rows"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentRequestDtoDataRemittanceData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in headings (list)
        _items = []
        if self.headings:
            for _item_headings in self.headings:
                if _item_headings:
                    _items.append(_item_headings.to_dict())
            _dict['headings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rows (list of list)
        _items = []
        if self.rows:
            for _item_rows in self.rows:
                if _item_rows:
                    _items.append(
                         [_inner_item.to_dict() for _inner_item in _item_rows if _inner_item is not None]
                    )
            _dict['rows'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentRequestDtoDataRemittanceData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "headings": [HeadingDto.from_dict(_item) for _item in obj["headings"]] if obj.get("headings") is not None else None,
            "rows": [
                    [RowDto.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["rows"]
                ] if obj.get("rows") is not None else None
        })
        return _obj


