# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.payment_intent_request_intent import PaymentIntentRequestIntent
from openapi_client.models.payment_intent_request_pfr import PaymentIntentRequestPfr
from openapi_client.models.payment_intent_request_reference_data_list_inner import PaymentIntentRequestReferenceDataListInner
from openapi_client.models.payment_intent_request_splits_inner import PaymentIntentRequestSplitsInner
from openapi_client.models.payment_intent_response_customers_inner import PaymentIntentResponseCustomersInner
from typing import Optional, Set
from typing_extensions import Self

class PaymentIntentResponse(BaseModel):
    """
    PaymentIntentResponse
    """ # noqa: E501
    payment_token: Optional[StrictStr] = Field(default=None, alias="paymentToken")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    title: Optional[StrictStr] = None
    short_description: Optional[StrictStr] = Field(default=None, alias="shortDescription")
    payment_description: Optional[StrictStr] = Field(default=None, alias="paymentDescription")
    invoice_number: Optional[StrictStr] = Field(default=None, alias="invoiceNumber")
    expires_on: Optional[StrictStr] = Field(default=None, alias="expiresOn")
    intent: Optional[PaymentIntentRequestIntent] = None
    save_for_future: Optional[StrictBool] = Field(default=None, alias="saveForFuture")
    enable_premium_finance: Optional[StrictBool] = Field(default=None, alias="enablePremiumFinance")
    splits: Optional[List[PaymentIntentRequestSplitsInner]] = None
    quote_key: Optional[StrictStr] = Field(default=None, alias="quoteKey")
    account_number: Optional[StrictStr] = Field(default=None, alias="accountNumber")
    suppress_technology_fee: Optional[StrictBool] = Field(default=None, alias="suppressTechnologyFee")
    override_technology_fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="overrideTechnologyFee")
    is_premium_financier: Optional[StrictBool] = Field(default=None, alias="isPremiumFinancier")
    pfr: Optional[PaymentIntentRequestPfr] = None
    customers: Optional[List[PaymentIntentResponseCustomersInner]] = None
    additional_details_preference: Optional[StrictStr] = Field(default=None, alias="additionalDetailsPreference")
    selected_customer_fields: Optional[StrictStr] = Field(default=None, alias="selectedCustomerFields")
    reference_data_list: Optional[List[PaymentIntentRequestReferenceDataListInner]] = Field(default=None, alias="referenceDataList")
    display_mode: Optional[StrictStr] = Field(default=None, alias="displayMode")
    __properties: ClassVar[List[str]] = ["paymentToken", "amount", "title", "shortDescription", "paymentDescription", "invoiceNumber", "expiresOn", "intent", "saveForFuture", "enablePremiumFinance", "splits", "quoteKey", "accountNumber", "suppressTechnologyFee", "overrideTechnologyFee", "isPremiumFinancier", "pfr", "customers", "additionalDetailsPreference", "selectedCustomerFields", "referenceDataList", "displayMode"]

    @field_validator('additional_details_preference')
    def additional_details_preference_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'AskShopper', 'ManualEnter', 'NoAdditionalDetails', 'ManualEnterEditNotAllowed']):
            raise ValueError("must be one of enum values ('None', 'AskShopper', 'ManualEnter', 'NoAdditionalDetails', 'ManualEnterEditNotAllowed')")
        return value

    @field_validator('display_mode')
    def display_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'PremiumFinanceOnly', 'Both']):
            raise ValueError("must be one of enum values ('None', 'PremiumFinanceOnly', 'Both')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentIntentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of intent
        if self.intent:
            _dict['intent'] = self.intent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in splits (list)
        _items = []
        if self.splits:
            for _item_splits in self.splits:
                if _item_splits:
                    _items.append(_item_splits.to_dict())
            _dict['splits'] = _items
        # override the default output from pydantic by calling `to_dict()` of pfr
        if self.pfr:
            _dict['pfr'] = self.pfr.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in customers (list)
        _items = []
        if self.customers:
            for _item_customers in self.customers:
                if _item_customers:
                    _items.append(_item_customers.to_dict())
            _dict['customers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reference_data_list (list)
        _items = []
        if self.reference_data_list:
            for _item_reference_data_list in self.reference_data_list:
                if _item_reference_data_list:
                    _items.append(_item_reference_data_list.to_dict())
            _dict['referenceDataList'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentIntentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "paymentToken": obj.get("paymentToken"),
            "amount": obj.get("amount"),
            "title": obj.get("title"),
            "shortDescription": obj.get("shortDescription"),
            "paymentDescription": obj.get("paymentDescription"),
            "invoiceNumber": obj.get("invoiceNumber"),
            "expiresOn": obj.get("expiresOn"),
            "intent": PaymentIntentRequestIntent.from_dict(obj["intent"]) if obj.get("intent") is not None else None,
            "saveForFuture": obj.get("saveForFuture"),
            "enablePremiumFinance": obj.get("enablePremiumFinance"),
            "splits": [PaymentIntentRequestSplitsInner.from_dict(_item) for _item in obj["splits"]] if obj.get("splits") is not None else None,
            "quoteKey": obj.get("quoteKey"),
            "accountNumber": obj.get("accountNumber"),
            "suppressTechnologyFee": obj.get("suppressTechnologyFee"),
            "overrideTechnologyFee": obj.get("overrideTechnologyFee"),
            "isPremiumFinancier": obj.get("isPremiumFinancier"),
            "pfr": PaymentIntentRequestPfr.from_dict(obj["pfr"]) if obj.get("pfr") is not None else None,
            "customers": [PaymentIntentResponseCustomersInner.from_dict(_item) for _item in obj["customers"]] if obj.get("customers") is not None else None,
            "additionalDetailsPreference": obj.get("additionalDetailsPreference"),
            "selectedCustomerFields": obj.get("selectedCustomerFields"),
            "referenceDataList": [PaymentIntentRequestReferenceDataListInner.from_dict(_item) for _item in obj["referenceDataList"]] if obj.get("referenceDataList") is not None else None,
            "displayMode": obj.get("displayMode")
        })
        return _obj


