# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PaymentDetailResponseDTO(BaseModel):
    """
    PaymentDetailResponseDTO
    """ # noqa: E501
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    vendor_id: Optional[StrictStr] = Field(default=None, alias="vendorId")
    vendor_name: Optional[StrictStr] = Field(default=None, alias="vendorName")
    merchant_dba_name: Optional[StrictStr] = Field(default=None, alias="merchantDBAName")
    payment_id: Optional[StrictStr] = Field(default=None, alias="paymentId")
    check_number: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="checkNumber")
    payment_method: Optional[StrictStr] = Field(default=None, alias="paymentMethod")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    bank_name: Optional[StrictStr] = Field(default=None, alias="bankName")
    bank_account_number: Optional[StrictStr] = Field(default=None, alias="bankAccountNumber")
    payment_status: Optional[StrictStr] = Field(default=None, alias="paymentStatus")
    payment_method_status: Optional[StrictStr] = Field(default=None, alias="paymentMethodStatus")
    remittance_data: Optional[StrictStr] = Field(default=None, alias="remittanceData")
    __properties: ClassVar[List[str]] = ["merchantId", "vendorId", "vendorName", "merchantDBAName", "paymentId", "checkNumber", "paymentMethod", "amount", "bankName", "bankAccountNumber", "paymentStatus", "paymentMethodStatus", "remittanceData"]

    @field_validator('payment_method')
    def payment_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Check']):
            raise ValueError("must be one of enum values ('Check')")
        return value

    @field_validator('payment_status')
    def payment_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'Created', 'InProcess', 'Success', 'Cancelled', 'Failed', 'CancelRequested']):
            raise ValueError("must be one of enum values ('NA', 'Created', 'InProcess', 'Success', 'Cancelled', 'Failed', 'CancelRequested')")
        return value

    @field_validator('payment_method_status')
    def payment_method_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'Accepted', 'PrintQueued', 'Printed', 'Mailed', 'Delivered', 'Pdf', 'Cancelled', 'Warning', 'Failed', 'Returned', 'Transit']):
            raise ValueError("must be one of enum values ('NA', 'Accepted', 'PrintQueued', 'Printed', 'Mailed', 'Delivered', 'Pdf', 'Cancelled', 'Warning', 'Failed', 'Returned', 'Transit')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentDetailResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentDetailResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchantId": obj.get("merchantId"),
            "vendorId": obj.get("vendorId"),
            "vendorName": obj.get("vendorName"),
            "merchantDBAName": obj.get("merchantDBAName"),
            "paymentId": obj.get("paymentId"),
            "checkNumber": obj.get("checkNumber"),
            "paymentMethod": obj.get("paymentMethod"),
            "amount": obj.get("amount"),
            "bankName": obj.get("bankName"),
            "bankAccountNumber": obj.get("bankAccountNumber"),
            "paymentStatus": obj.get("paymentStatus"),
            "paymentMethodStatus": obj.get("paymentMethodStatus"),
            "remittanceData": obj.get("remittanceData")
        })
        return _obj


