# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.data_dto import DataDto
from typing import Optional, Set
from typing_extensions import Self

class PaymentResponseDto(BaseModel):
    """
    PaymentResponseDto
    """ # noqa: E501
    id: Optional[StrictStr] = None
    payment_id: Optional[StrictStr] = Field(default=None, alias="paymentId")
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    vendor_id: Optional[StrictStr] = Field(default=None, alias="vendorId")
    payment_status: Optional[StrictStr] = Field(default=None, alias="paymentStatus")
    payment_method_status: Optional[StrictStr] = Field(default=None, alias="paymentMethodStatus")
    payment_method: Optional[StrictStr] = Field(default=None, alias="paymentMethod")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    data: Optional[DataDto] = None
    bank_account_details: Optional[StrictStr] = Field(default=None, description="JSON-encoded string containing bank account details", alias="bankAccountDetails")
    vendor_address: Optional[StrictStr] = Field(default=None, description="JSON-encoded string containing vendor address", alias="vendorAddress")
    __properties: ClassVar[List[str]] = ["id", "paymentId", "merchantId", "vendorId", "paymentStatus", "paymentMethodStatus", "paymentMethod", "amount", "data", "bankAccountDetails", "vendorAddress"]

    @field_validator('payment_status')
    def payment_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'Created', 'InProcess', 'Success', 'Cancelled', 'Failed', 'CancelRequested']):
            raise ValueError("must be one of enum values ('NA', 'Created', 'InProcess', 'Success', 'Cancelled', 'Failed', 'CancelRequested')")
        return value

    @field_validator('payment_method_status')
    def payment_method_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'Accepted', 'PrintQueued', 'Printed', 'Mailed', 'Delivered', 'Pdf', 'Cancelled', 'Warning', 'Failed', 'Returned', 'Transit']):
            raise ValueError("must be one of enum values ('NA', 'Accepted', 'PrintQueued', 'Printed', 'Mailed', 'Delivered', 'Pdf', 'Cancelled', 'Warning', 'Failed', 'Returned', 'Transit')")
        return value

    @field_validator('payment_method')
    def payment_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Check']):
            raise ValueError("must be one of enum values ('Check')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "paymentId": obj.get("paymentId"),
            "merchantId": obj.get("merchantId"),
            "vendorId": obj.get("vendorId"),
            "paymentStatus": obj.get("paymentStatus"),
            "paymentMethodStatus": obj.get("paymentMethodStatus"),
            "paymentMethod": obj.get("paymentMethod"),
            "amount": obj.get("amount"),
            "data": DataDto.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "bankAccountDetails": obj.get("bankAccountDetails"),
            "vendorAddress": obj.get("vendorAddress")
        })
        return _obj


