# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.payment_batch_details_response_transaction_details_inner import PaymentBatchDetailsResponseTransactionDetailsInner
from typing import Optional, Set
from typing_extensions import Self

class PaymentBatchDetailsResponse(BaseModel):
    """
    PaymentBatchDetailsResponse
    """ # noqa: E501
    batch_id: Optional[StrictStr] = Field(default=None, alias="batchId")
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    batch_status: Optional[StrictStr] = Field(default=None, alias="batchStatus")
    process_methods: Optional[StrictStr] = Field(default=None, alias="processMethods")
    processor_name: Optional[StrictStr] = Field(default=None, alias="processorName")
    is_default: Optional[StrictBool] = Field(default=None, alias="isDefault")
    executed_on_demand: Optional[StrictBool] = Field(default=None, alias="executedOnDemand")
    execution_time: Optional[StrictStr] = Field(default=None, alias="executionTime")
    completion_time: Optional[StrictStr] = Field(default=None, alias="completionTime")
    created_on: Optional[StrictStr] = Field(default=None, alias="createdOn")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    modified_on: Optional[StrictStr] = Field(default=None, alias="modifiedOn")
    modified_by: Optional[StrictStr] = Field(default=None, alias="modifiedBy")
    capture_count: Optional[StrictInt] = Field(default=None, alias="captureCount")
    capture_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="captureAmount")
    voided_count: Optional[StrictInt] = Field(default=None, alias="voidedCount")
    voided_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="voidedAmount")
    total_live_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalLiveAmount")
    refunded_count: Optional[StrictInt] = Field(default=None, alias="refundedCount")
    refunded_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="refundedAmount")
    chargeback_count: Optional[StrictInt] = Field(default=None, alias="chargebackCount")
    chargeback_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="chargebackAmount")
    transaction_details: Optional[List[PaymentBatchDetailsResponseTransactionDetailsInner]] = Field(default=None, alias="transactionDetails")
    __properties: ClassVar[List[str]] = ["batchId", "merchantId", "batchStatus", "processMethods", "processorName", "isDefault", "executedOnDemand", "executionTime", "completionTime", "createdOn", "createdBy", "modifiedOn", "modifiedBy", "captureCount", "captureAmount", "voidedCount", "voidedAmount", "totalLiveAmount", "refundedCount", "refundedAmount", "chargebackCount", "chargebackAmount", "transactionDetails"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentBatchDetailsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in transaction_details (list)
        _items = []
        if self.transaction_details:
            for _item_transaction_details in self.transaction_details:
                if _item_transaction_details:
                    _items.append(_item_transaction_details.to_dict())
            _dict['transactionDetails'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentBatchDetailsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "batchId": obj.get("batchId"),
            "merchantId": obj.get("merchantId"),
            "batchStatus": obj.get("batchStatus"),
            "processMethods": obj.get("processMethods"),
            "processorName": obj.get("processorName"),
            "isDefault": obj.get("isDefault"),
            "executedOnDemand": obj.get("executedOnDemand"),
            "executionTime": obj.get("executionTime"),
            "completionTime": obj.get("completionTime"),
            "createdOn": obj.get("createdOn"),
            "createdBy": obj.get("createdBy"),
            "modifiedOn": obj.get("modifiedOn"),
            "modifiedBy": obj.get("modifiedBy"),
            "captureCount": obj.get("captureCount"),
            "captureAmount": obj.get("captureAmount"),
            "voidedCount": obj.get("voidedCount"),
            "voidedAmount": obj.get("voidedAmount"),
            "totalLiveAmount": obj.get("totalLiveAmount"),
            "refundedCount": obj.get("refundedCount"),
            "refundedAmount": obj.get("refundedAmount"),
            "chargebackCount": obj.get("chargebackCount"),
            "chargebackAmount": obj.get("chargebackAmount"),
            "transactionDetails": [PaymentBatchDetailsResponseTransactionDetailsInner.from_dict(_item) for _item in obj["transactionDetails"]] if obj.get("transactionDetails") is not None else None
        })
        return _obj


