# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.pf_endorsement_request_quote_insured_address import PFEndorsementRequestQuoteInsuredAddress
from typing import Optional, Set
from typing_extensions import Self

class PFEndorsementRequestQuoteInsured(BaseModel):
    """
    PFEndorsementRequestQuoteInsured
    """ # noqa: E501
    agent_customer_number: Optional[StrictStr] = Field(default=None, description="This denotes the Agent Customer Number.", alias="AgentCustomerNumber")
    email: Optional[StrictStr] = Field(default=None, description="This denotes the email.", alias="Email")
    care_of: Optional[StrictStr] = Field(default=None, description="This denotes the care of.", alias="CareOf")
    unique_id: Optional[StrictStr] = Field(default=None, description="This denotes a unique identifier for the insured.", alias="UniqueID")
    mobile_phone_number: Optional[StrictStr] = Field(default=None, description="This denotes the mobile phone number.", alias="MobilePhoneNumber")
    is_cancellation_warning_enabled: Optional[StrictBool] = Field(default=None, description="Indicates if cancellation warnings are enabled.", alias="IsCancellationWarningEnabled")
    fax_number: Optional[StrictStr] = Field(default=None, description="This denotes the fax number.", alias="FaxNumber")
    email_address: Optional[StrictStr] = Field(default=None, description="This denotes an alternate email address.", alias="EmailAddress")
    pf_type: Optional[StrictStr] = Field(default=None, description="This denotes the PFType (enum or string depending on your definition).", alias="PFType")
    address: Optional[PFEndorsementRequestQuoteInsuredAddress] = Field(default=None, alias="Address")
    has_data_change_agent_customer_number: Optional[StrictBool] = Field(default=None, alias="HasDataChangeAgentCustomerNumber")
    has_data_change_name: Optional[StrictBool] = Field(default=None, alias="HasDataChangeName")
    has_data_change_address1: Optional[StrictBool] = Field(default=None, alias="HasDataChangeAddress1")
    has_data_change_address2: Optional[StrictBool] = Field(default=None, alias="HasDataChangeAddress2")
    has_data_change_city: Optional[StrictBool] = Field(default=None, alias="HasDataChangeCity")
    has_data_change_state: Optional[StrictBool] = Field(default=None, alias="HasDataChangeState")
    has_data_change_zip: Optional[StrictBool] = Field(default=None, alias="HasDataChangeZip")
    has_data_change_phone: Optional[StrictBool] = Field(default=None, alias="HasDataChangePhone")
    has_data_change_email: Optional[StrictBool] = Field(default=None, alias="HasDataChangeEmail")
    has_data_change_care_of: Optional[StrictBool] = Field(default=None, alias="HasDataChangeCareOf")
    has_data_change_insured: Optional[StrictBool] = Field(default=None, alias="HasDataChangeInsured")
    __properties: ClassVar[List[str]] = ["AgentCustomerNumber", "Email", "CareOf", "UniqueID", "MobilePhoneNumber", "IsCancellationWarningEnabled", "FaxNumber", "EmailAddress", "PFType", "Address", "HasDataChangeAgentCustomerNumber", "HasDataChangeName", "HasDataChangeAddress1", "HasDataChangeAddress2", "HasDataChangeCity", "HasDataChangeState", "HasDataChangeZip", "HasDataChangePhone", "HasDataChangeEmail", "HasDataChangeCareOf", "HasDataChangeInsured"]

    @field_validator('pf_type')
    def pf_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'EPF', 'PFLite']):
            raise ValueError("must be one of enum values ('None', 'EPF', 'PFLite')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFEndorsementRequestQuoteInsured from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['Address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFEndorsementRequestQuoteInsured from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AgentCustomerNumber": obj.get("AgentCustomerNumber"),
            "Email": obj.get("Email"),
            "CareOf": obj.get("CareOf"),
            "UniqueID": obj.get("UniqueID"),
            "MobilePhoneNumber": obj.get("MobilePhoneNumber"),
            "IsCancellationWarningEnabled": obj.get("IsCancellationWarningEnabled"),
            "FaxNumber": obj.get("FaxNumber"),
            "EmailAddress": obj.get("EmailAddress"),
            "PFType": obj.get("PFType"),
            "Address": PFEndorsementRequestQuoteInsuredAddress.from_dict(obj["Address"]) if obj.get("Address") is not None else None,
            "HasDataChangeAgentCustomerNumber": obj.get("HasDataChangeAgentCustomerNumber"),
            "HasDataChangeName": obj.get("HasDataChangeName"),
            "HasDataChangeAddress1": obj.get("HasDataChangeAddress1"),
            "HasDataChangeAddress2": obj.get("HasDataChangeAddress2"),
            "HasDataChangeCity": obj.get("HasDataChangeCity"),
            "HasDataChangeState": obj.get("HasDataChangeState"),
            "HasDataChangeZip": obj.get("HasDataChangeZip"),
            "HasDataChangePhone": obj.get("HasDataChangePhone"),
            "HasDataChangeEmail": obj.get("HasDataChangeEmail"),
            "HasDataChangeCareOf": obj.get("HasDataChangeCareOf"),
            "HasDataChangeInsured": obj.get("HasDataChangeInsured")
        })
        return _obj


