# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner(BaseModel):
    """
    PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner
    """ # noqa: E501
    pay_to: Optional[StrictStr] = Field(default=None, alias="payTo")
    payment_method: Optional[StrictStr] = Field(default=None, alias="paymentMethod")
    funding_type: Optional[StrictStr] = Field(default=None, alias="fundingType")
    bank_routing_number: Optional[StrictStr] = Field(default=None, alias="bankRoutingNumber")
    bank_acct_number: Optional[StrictStr] = Field(default=None, alias="bankAcctNumber")
    is_checking_account: Optional[StrictBool] = Field(default=None, alias="isCheckingAccount")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    funding_date: Optional[StrictStr] = Field(default=None, alias="fundingDate")
    __properties: ClassVar[List[str]] = ["payTo", "paymentMethod", "fundingType", "bankRoutingNumber", "bankAcctNumber", "isCheckingAccount", "amount", "fundingDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFEndorsementRequestQuotePoliciesInnerTotalPayFundingInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "payTo": obj.get("payTo"),
            "paymentMethod": obj.get("paymentMethod"),
            "fundingType": obj.get("fundingType"),
            "bankRoutingNumber": obj.get("bankRoutingNumber"),
            "bankAcctNumber": obj.get("bankAcctNumber"),
            "isCheckingAccount": obj.get("isCheckingAccount"),
            "amount": obj.get("amount"),
            "fundingDate": obj.get("fundingDate")
        })
        return _obj


