# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.pf_endorsement_request_quote_details_recurring_ach import PFEndorsementRequestQuoteDetailsRecurringACH
from typing import Optional, Set
from typing_extensions import Self

class PFEndorsementRequestQuoteDetails(BaseModel):
    """
    PFEndorsementRequestQuoteDetails
    """ # noqa: E501
    commercial: Optional[StrictStr] = Field(default=None, description="This denotes the Commercial.")
    coupon: Optional[StrictStr] = Field(default=None, description="This denotes the Coupon.")
    coupon_invoice_printed: Optional[StrictBool] = Field(default=None, description="This denotes the flag if invoice printed or not.", alias="couponInvoicePrinted")
    crd: Optional[StrictInt] = Field(default=None, description="This denotes the Crd.")
    interval: Optional[StrictStr] = Field(default=None, description="This denotes the Interval.")
    installments: Optional[StrictInt] = Field(default=None, description="This denotes the number of installments.")
    program_id: Optional[StrictInt] = Field(default=None, description="This denotes the program ID.", alias="programID")
    broker_fee: Optional[StrictInt] = Field(default=None, description="This denotes the broker fees.", alias="brokerFee")
    e_sign_option: Optional[StrictStr] = Field(default=None, description="This denotes the eSign Option.", alias="eSignOption")
    process_down_payment: Optional[StrictBool] = Field(default=None, description="This denotes the flag that down payment is processed or not.", alias="processDownPayment")
    process_down_payment_no_reason: Optional[StrictStr] = Field(default=None, description="This denotes the Process Down Payment No Reason.", alias="processDownPaymentNoReason")
    down_payment_method: Optional[StrictStr] = Field(default=None, description="This denotes the Down Payment Method.", alias="downPaymentMethod")
    down_payment_paid_by: Optional[StrictStr] = Field(default=None, description="This denotes the Down Payment Paid by.", alias="downPaymentPaidBy")
    recurring_ach: Optional[PFEndorsementRequestQuoteDetailsRecurringACH] = Field(default=None, alias="recurringACH")
    batch_id: Optional[StrictStr] = Field(default=None, description="This denotes the batch ID.", alias="batchID")
    return_pfa: Optional[StrictBool] = Field(default=None, description="This denotes the flag whether to return PFA or not.", alias="returnPFA")
    equal_payments: Optional[StrictStr] = Field(default=None, description="This denotes the equal payments.", alias="equalPayments")
    quote_expiration_days: Optional[StrictInt] = Field(default=None, description="This denotes the number of days to expire.", alias="quoteExpirationDays")
    bypass_cadnb: Optional[StrictBool] = Field(default=None, description="This denotes the flag whether to bypass CADNB.", alias="bypassCADNB")
    allow_zero_apr: Optional[StrictBool] = Field(default=None, description="This denotes the Allow Zero APR.", alias="allowZeroAPR")
    associated_account_number: Optional[StrictStr] = Field(default=None, description="This denotes the associated account number.", alias="associatedAccountNumber")
    channel: Optional[StrictStr] = Field(default=None, description="This denotes the channel.")
    channel_version: Optional[StrictStr] = Field(default=None, description="This denotes the channel version.", alias="channelVersion")
    __properties: ClassVar[List[str]] = ["commercial", "coupon", "couponInvoicePrinted", "crd", "interval", "installments", "programID", "brokerFee", "eSignOption", "processDownPayment", "processDownPaymentNoReason", "downPaymentMethod", "downPaymentPaidBy", "recurringACH", "batchID", "returnPFA", "equalPayments", "quoteExpirationDays", "bypassCADNB", "allowZeroAPR", "associatedAccountNumber", "channel", "channelVersion"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFEndorsementRequestQuoteDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recurring_ach
        if self.recurring_ach:
            _dict['recurringACH'] = self.recurring_ach.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFEndorsementRequestQuoteDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "commercial": obj.get("commercial"),
            "coupon": obj.get("coupon"),
            "couponInvoicePrinted": obj.get("couponInvoicePrinted"),
            "crd": obj.get("crd"),
            "interval": obj.get("interval"),
            "installments": obj.get("installments"),
            "programID": obj.get("programID"),
            "brokerFee": obj.get("brokerFee"),
            "eSignOption": obj.get("eSignOption"),
            "processDownPayment": obj.get("processDownPayment"),
            "processDownPaymentNoReason": obj.get("processDownPaymentNoReason"),
            "downPaymentMethod": obj.get("downPaymentMethod"),
            "downPaymentPaidBy": obj.get("downPaymentPaidBy"),
            "recurringACH": PFEndorsementRequestQuoteDetailsRecurringACH.from_dict(obj["recurringACH"]) if obj.get("recurringACH") is not None else None,
            "batchID": obj.get("batchID"),
            "returnPFA": obj.get("returnPFA"),
            "equalPayments": obj.get("equalPayments"),
            "quoteExpirationDays": obj.get("quoteExpirationDays"),
            "bypassCADNB": obj.get("bypassCADNB"),
            "allowZeroAPR": obj.get("allowZeroAPR"),
            "associatedAccountNumber": obj.get("associatedAccountNumber"),
            "channel": obj.get("channel"),
            "channelVersion": obj.get("channelVersion")
        })
        return _obj


