# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.pf_endorsement_request_quote_insured_address import PFEndorsementRequestQuoteInsuredAddress
from typing import Optional, Set
from typing_extensions import Self

class PFEndorsementRequestQuoteInsured(BaseModel):
    """
    PFEndorsementRequestQuoteInsured
    """ # noqa: E501
    agent_customer_number: Optional[StrictStr] = Field(default=None, description="This denotes the Agent Customer Number.", alias="agentCustomerNumber")
    email: Optional[StrictStr] = Field(default=None, description="This denotes the email.")
    care_of: Optional[StrictStr] = Field(default=None, description="This denotes the care of.", alias="careOf")
    unique_id: Optional[StrictStr] = Field(default=None, description="This denotes a unique identifier for the insured.", alias="uniqueID")
    mobile_phone_number: Optional[StrictStr] = Field(default=None, description="This denotes the mobile phone number.", alias="mobilePhoneNumber")
    is_cancellation_warning_enabled: Optional[StrictBool] = Field(default=None, description="Indicates if cancellation warnings are enabled.", alias="isCancellationWarningEnabled")
    fax_number: Optional[StrictStr] = Field(default=None, description="This denotes the fax number.", alias="faxNumber")
    email_address: Optional[StrictStr] = Field(default=None, description="This denotes an alternate email address.", alias="emailAddress")
    pf_type: Optional[StrictStr] = Field(default=None, description="This denotes the PFType (enum or string depending on your definition).", alias="pfType")
    address: Optional[PFEndorsementRequestQuoteInsuredAddress] = None
    has_data_change_agent_customer_number: Optional[StrictBool] = Field(default=None, alias="hasDataChangeAgentCustomerNumber")
    has_data_change_name: Optional[StrictBool] = Field(default=None, alias="hasDataChangeName")
    has_data_change_address1: Optional[StrictBool] = Field(default=None, alias="hasDataChangeAddress1")
    has_data_change_address2: Optional[StrictBool] = Field(default=None, alias="hasDataChangeAddress2")
    has_data_change_city: Optional[StrictBool] = Field(default=None, alias="hasDataChangeCity")
    has_data_change_state: Optional[StrictBool] = Field(default=None, alias="hasDataChangeState")
    has_data_change_zip: Optional[StrictBool] = Field(default=None, alias="hasDataChangeZip")
    has_data_change_phone: Optional[StrictBool] = Field(default=None, alias="hasDataChangePhone")
    has_data_change_email: Optional[StrictBool] = Field(default=None, alias="hasDataChangeEmail")
    has_data_change_care_of: Optional[StrictBool] = Field(default=None, alias="hasDataChangeCareOf")
    has_data_change_insured: Optional[StrictBool] = Field(default=None, alias="hasDataChangeInsured")
    __properties: ClassVar[List[str]] = ["agentCustomerNumber", "email", "careOf", "uniqueID", "mobilePhoneNumber", "isCancellationWarningEnabled", "faxNumber", "emailAddress", "pfType", "address", "hasDataChangeAgentCustomerNumber", "hasDataChangeName", "hasDataChangeAddress1", "hasDataChangeAddress2", "hasDataChangeCity", "hasDataChangeState", "hasDataChangeZip", "hasDataChangePhone", "hasDataChangeEmail", "hasDataChangeCareOf", "hasDataChangeInsured"]

    @field_validator('pf_type')
    def pf_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'EPF', 'PFLite']):
            raise ValueError("must be one of enum values ('None', 'EPF', 'PFLite')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFEndorsementRequestQuoteInsured from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFEndorsementRequestQuoteInsured from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agentCustomerNumber": obj.get("agentCustomerNumber"),
            "email": obj.get("email"),
            "careOf": obj.get("careOf"),
            "uniqueID": obj.get("uniqueID"),
            "mobilePhoneNumber": obj.get("mobilePhoneNumber"),
            "isCancellationWarningEnabled": obj.get("isCancellationWarningEnabled"),
            "faxNumber": obj.get("faxNumber"),
            "emailAddress": obj.get("emailAddress"),
            "pfType": obj.get("pfType"),
            "address": PFEndorsementRequestQuoteInsuredAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "hasDataChangeAgentCustomerNumber": obj.get("hasDataChangeAgentCustomerNumber"),
            "hasDataChangeName": obj.get("hasDataChangeName"),
            "hasDataChangeAddress1": obj.get("hasDataChangeAddress1"),
            "hasDataChangeAddress2": obj.get("hasDataChangeAddress2"),
            "hasDataChangeCity": obj.get("hasDataChangeCity"),
            "hasDataChangeState": obj.get("hasDataChangeState"),
            "hasDataChangeZip": obj.get("hasDataChangeZip"),
            "hasDataChangePhone": obj.get("hasDataChangePhone"),
            "hasDataChangeEmail": obj.get("hasDataChangeEmail"),
            "hasDataChangeCareOf": obj.get("hasDataChangeCareOf"),
            "hasDataChangeInsured": obj.get("hasDataChangeInsured")
        })
        return _obj


