# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.pf_endorsement_response_item_payment_intent_intent import PFEndorsementResponseItemPaymentIntentIntent
from typing import Optional, Set
from typing_extensions import Self

class PFEndorsementResponseItemPaymentIntent(BaseModel):
    """
    PFEndorsementResponseItemPaymentIntent
    """ # noqa: E501
    payment_token: Optional[StrictStr] = Field(default=None, alias="paymentToken")
    title: Optional[StrictStr] = None
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    invoice_number: Optional[StrictStr] = Field(default=None, alias="invoiceNumber")
    expire_on: Optional[StrictStr] = Field(default=None, alias="expireOn")
    short_description: Optional[StrictStr] = Field(default=None, alias="shortDescription")
    payment_description: Optional[StrictStr] = Field(default=None, alias="paymentDescription")
    intent: Optional[PFEndorsementResponseItemPaymentIntentIntent] = None
    __properties: ClassVar[List[str]] = ["paymentToken", "title", "amount", "invoiceNumber", "expireOn", "shortDescription", "paymentDescription", "intent"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFEndorsementResponseItemPaymentIntent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of intent
        if self.intent:
            _dict['intent'] = self.intent.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFEndorsementResponseItemPaymentIntent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "paymentToken": obj.get("paymentToken"),
            "title": obj.get("title"),
            "amount": obj.get("amount"),
            "invoiceNumber": obj.get("invoiceNumber"),
            "expireOn": obj.get("expireOn"),
            "shortDescription": obj.get("shortDescription"),
            "paymentDescription": obj.get("paymentDescription"),
            "intent": PFEndorsementResponseItemPaymentIntentIntent.from_dict(obj["intent"]) if obj.get("intent") is not None else None
        })
        return _obj


