# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.pf_lite_payment_link_request_customers_inner_address import PFLitePaymentLinkRequestCustomersInnerAddress
from typing import Optional, Set
from typing_extensions import Self

class PFLitePaymentLinkRequestCustomersInner(BaseModel):
    """
    PFLitePaymentLinkRequestCustomersInner
    """ # noqa: E501
    first_name: StrictStr = Field(alias="firstName")
    last_name: StrictStr = Field(alias="lastName")
    email: StrictStr
    phone: StrictStr
    phone_country_code: Optional[StrictStr] = Field(default=None, alias="phoneCountryCode")
    address: Optional[PFLitePaymentLinkRequestCustomersInnerAddress] = None
    notify_via_sms: Optional[StrictBool] = Field(default=None, alias="notifyViaSMS")
    notify_via_email: Optional[StrictBool] = Field(default=None, alias="notifyViaEmail")
    __properties: ClassVar[List[str]] = ["firstName", "lastName", "email", "phone", "phoneCountryCode", "address", "notifyViaSMS", "notifyViaEmail"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFLitePaymentLinkRequestCustomersInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFLitePaymentLinkRequestCustomersInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "phoneCountryCode": obj.get("phoneCountryCode"),
            "address": PFLitePaymentLinkRequestCustomersInnerAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "notifyViaSMS": obj.get("notifyViaSMS"),
            "notifyViaEmail": obj.get("notifyViaEmail")
        })
        return _obj


