# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.pf_lite_generate_quote_response_item_e_sign_result import PFLiteGenerateQuoteResponseItemESignResult
from typing import Optional, Set
from typing_extensions import Self

class PFLiteGenerateQuoteResponseItem(BaseModel):
    """
    PFLiteGenerateQuoteResponseItem
    """ # noqa: E501
    quote_key: Optional[StrictInt] = Field(default=None, alias="quoteKey")
    premium: Optional[Union[StrictFloat, StrictInt]] = None
    down_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="downAmount")
    amount_financed: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="amountFinanced")
    finance_charge: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="financeCharge")
    total_payments: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalPayments")
    payment_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="paymentAmount")
    doc_stamp: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="docStamp")
    first_due_date: Optional[StrictStr] = Field(default=None, alias="firstDueDate")
    apr: Optional[Union[StrictFloat, StrictInt]] = None
    installments: Optional[StrictInt] = None
    batch_id: Optional[StrictStr] = Field(default=None, alias="batchId")
    payments_retained: Optional[StrictInt] = Field(default=None, alias="paymentsRetained")
    payment_retained_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="paymentRetainedAmount")
    unsigned_pfa_url: Optional[StrictStr] = Field(default=None, alias="unsignedPFAUrl")
    retail_agent_register_login_url: Optional[StrictStr] = Field(default=None, alias="retailAgentRegisterLoginURL")
    e_sign_result: Optional[PFLiteGenerateQuoteResponseItemESignResult] = Field(default=None, alias="eSignResult")
    errors: Optional[StrictStr] = None
    pfa: Optional[StrictStr] = None
    electronic_signature_url: Optional[StrictStr] = Field(default=None, alias="electronicSignatureURL")
    offer_auto_pay: Optional[StrictBool] = Field(default=None, alias="offerAutoPay")
    __properties: ClassVar[List[str]] = ["quoteKey", "premium", "downAmount", "amountFinanced", "financeCharge", "totalPayments", "paymentAmount", "docStamp", "firstDueDate", "apr", "installments", "batchId", "paymentsRetained", "paymentRetainedAmount", "unsignedPFAUrl", "retailAgentRegisterLoginURL", "eSignResult", "errors", "pfa", "electronicSignatureURL", "offerAutoPay"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFLiteGenerateQuoteResponseItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of e_sign_result
        if self.e_sign_result:
            _dict['eSignResult'] = self.e_sign_result.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFLiteGenerateQuoteResponseItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quoteKey": obj.get("quoteKey"),
            "premium": obj.get("premium"),
            "downAmount": obj.get("downAmount"),
            "amountFinanced": obj.get("amountFinanced"),
            "financeCharge": obj.get("financeCharge"),
            "totalPayments": obj.get("totalPayments"),
            "paymentAmount": obj.get("paymentAmount"),
            "docStamp": obj.get("docStamp"),
            "firstDueDate": obj.get("firstDueDate"),
            "apr": obj.get("apr"),
            "installments": obj.get("installments"),
            "batchId": obj.get("batchId"),
            "paymentsRetained": obj.get("paymentsRetained"),
            "paymentRetainedAmount": obj.get("paymentRetainedAmount"),
            "unsignedPFAUrl": obj.get("unsignedPFAUrl"),
            "retailAgentRegisterLoginURL": obj.get("retailAgentRegisterLoginURL"),
            "eSignResult": PFLiteGenerateQuoteResponseItemESignResult.from_dict(obj["eSignResult"]) if obj.get("eSignResult") is not None else None,
            "errors": obj.get("errors"),
            "pfa": obj.get("pfa"),
            "electronicSignatureURL": obj.get("electronicSignatureURL"),
            "offerAutoPay": obj.get("offerAutoPay")
        })
        return _obj


