# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.pf_lite_payment_link_request_callback_parameters import PFLitePaymentLinkRequestCallbackParameters
from openapi_client.models.pf_lite_payment_link_request_customers_inner import PFLitePaymentLinkRequestCustomersInner
from openapi_client.models.pf_lite_payment_link_request_reference_data_list_inner import PFLitePaymentLinkRequestReferenceDataListInner
from openapi_client.models.pf_lite_payment_link_request_settings import PFLitePaymentLinkRequestSettings
from typing import Optional, Set
from typing_extensions import Self

class PFLitePaymentLinkRequest(BaseModel):
    """
    PFLitePaymentLinkRequest
    """ # noqa: E501
    quote_key: StrictStr = Field(alias="quoteKey")
    is_pay_in_full: Optional[StrictBool] = Field(default=None, alias="isPayInFull")
    title: StrictStr
    payment_description: StrictStr = Field(alias="paymentDescription")
    expire_in: StrictInt = Field(alias="expireIn")
    expire_in_unit: StrictStr = Field(alias="expireInUnit")
    reference_data_list: List[PFLitePaymentLinkRequestReferenceDataListInner] = Field(alias="referenceDataList")
    callback_parameters: Optional[PFLitePaymentLinkRequestCallbackParameters] = Field(default=None, alias="callbackParameters")
    customers: Optional[List[PFLitePaymentLinkRequestCustomersInner]] = None
    settings: PFLitePaymentLinkRequestSettings
    __properties: ClassVar[List[str]] = ["quoteKey", "isPayInFull", "title", "paymentDescription", "expireIn", "expireInUnit", "referenceDataList", "callbackParameters", "customers", "settings"]

    @field_validator('expire_in_unit')
    def expire_in_unit_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['NA', 'Seconds', 'Minutes', 'Hours', 'Days', 'Weeks']):
            raise ValueError("must be one of enum values ('NA', 'Seconds', 'Minutes', 'Hours', 'Days', 'Weeks')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFLitePaymentLinkRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reference_data_list (list)
        _items = []
        if self.reference_data_list:
            for _item_reference_data_list in self.reference_data_list:
                if _item_reference_data_list:
                    _items.append(_item_reference_data_list.to_dict())
            _dict['referenceDataList'] = _items
        # override the default output from pydantic by calling `to_dict()` of callback_parameters
        if self.callback_parameters:
            _dict['callbackParameters'] = self.callback_parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in customers (list)
        _items = []
        if self.customers:
            for _item_customers in self.customers:
                if _item_customers:
                    _items.append(_item_customers.to_dict())
            _dict['customers'] = _items
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFLitePaymentLinkRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quoteKey": obj.get("quoteKey"),
            "isPayInFull": obj.get("isPayInFull"),
            "title": obj.get("title"),
            "paymentDescription": obj.get("paymentDescription"),
            "expireIn": obj.get("expireIn"),
            "expireInUnit": obj.get("expireInUnit"),
            "referenceDataList": [PFLitePaymentLinkRequestReferenceDataListInner.from_dict(_item) for _item in obj["referenceDataList"]] if obj.get("referenceDataList") is not None else None,
            "callbackParameters": PFLitePaymentLinkRequestCallbackParameters.from_dict(obj["callbackParameters"]) if obj.get("callbackParameters") is not None else None,
            "customers": [PFLitePaymentLinkRequestCustomersInner.from_dict(_item) for _item in obj["customers"]] if obj.get("customers") is not None else None,
            "settings": PFLitePaymentLinkRequestSettings.from_dict(obj["settings"]) if obj.get("settings") is not None else None
        })
        return _obj


