# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PFRetrievePFAResponse(BaseModel):
    """
    PFRetrievePFAResponse
    """ # noqa: E501
    pfa: Optional[StrictStr] = Field(default=None, description="The PFA document.")
    mimetype: Optional[StrictStr] = Field(default=None, description="The MIME type of the PFA document.")
    extension: Optional[StrictStr] = Field(default=None, description="The file extension of the PFA document.")
    filename: Optional[StrictStr] = Field(default=None, description="The filename of the PFA document.")
    message: Optional[StrictStr] = Field(default=None, description="A message related to the PFA retrieval.")
    is_success: Optional[StrictBool] = Field(default=None, description="Indicates if the retrieval was successful.", alias="isSuccess")
    integration_id: Optional[StrictStr] = Field(default=None, description="The integration ID associated with the PFA retrieval.", alias="integrationID")
    __properties: ClassVar[List[str]] = ["pfa", "mimetype", "extension", "filename", "message", "isSuccess", "integrationID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PFRetrievePFAResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PFRetrievePFAResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pfa": obj.get("pfa"),
            "mimetype": obj.get("mimetype"),
            "extension": obj.get("extension"),
            "filename": obj.get("filename"),
            "message": obj.get("message"),
            "isSuccess": obj.get("isSuccess"),
            "integrationID": obj.get("integrationID")
        })
        return _obj


