# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.payment_intent_response_intent import PaymentIntentResponseIntent
from openapi_client.models.payment_link_response_callback_parameters import PaymentLinkResponseCallbackParameters
from typing import Optional, Set
from typing_extensions import Self

class SecureTokenLinkUpdateRequest(BaseModel):
    """
    SecureTokenLinkUpdateRequest
    """ # noqa: E501
    token_link_id: StrictStr = Field(alias="tokenLinkId")
    expire_in: StrictInt = Field(alias="expireIn")
    response_type: Optional[StrictStr] = Field(default=None, alias="responseType")
    expire_in_unit: StrictStr = Field(alias="expireInUnit")
    intent: PaymentIntentResponseIntent
    call_back_parameters: Optional[PaymentLinkResponseCallbackParameters] = Field(default=None, alias="callBackParameters")
    __properties: ClassVar[List[str]] = ["tokenLinkId", "expireIn", "responseType", "expireInUnit", "intent", "callBackParameters"]

    @field_validator('response_type')
    def response_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['OnScreen', 'CallBack']):
            raise ValueError("must be one of enum values ('OnScreen', 'CallBack')")
        return value

    @field_validator('expire_in_unit')
    def expire_in_unit_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Seconds', 'Minutes', 'Hours', 'Days', 'Weeks', 'NA']):
            raise ValueError("must be one of enum values ('Seconds', 'Minutes', 'Hours', 'Days', 'Weeks', 'NA')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SecureTokenLinkUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of intent
        if self.intent:
            _dict['intent'] = self.intent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of call_back_parameters
        if self.call_back_parameters:
            _dict['callBackParameters'] = self.call_back_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SecureTokenLinkUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tokenLinkId": obj.get("tokenLinkId"),
            "expireIn": obj.get("expireIn"),
            "responseType": obj.get("responseType"),
            "expireInUnit": obj.get("expireInUnit"),
            "intent": PaymentIntentResponseIntent.from_dict(obj["intent"]) if obj.get("intent") is not None else None,
            "callBackParameters": PaymentLinkResponseCallbackParameters.from_dict(obj["callBackParameters"]) if obj.get("callBackParameters") is not None else None
        })
        return _obj


