# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SecureTokenLinkByIdResponseTimeLineInner(BaseModel):
    """
    SecureTokenLinkByIdResponseTimeLineInner
    """ # noqa: E501
    id: Optional[StrictStr] = None
    token_link_id: Optional[StrictStr] = Field(default=None, alias="tokenLinkId")
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    payment_link_type: Optional[StrictStr] = Field(default=None, alias="paymentLinkType")
    link_status: Optional[StrictStr] = Field(default=None, alias="linkStatus")
    token_link_status: Optional[StrictStr] = Field(default=None, alias="tokenLinkStatus")
    event_date: Optional[StrictStr] = Field(default=None, alias="eventDate")
    __properties: ClassVar[List[str]] = ["id", "tokenLinkId", "merchantId", "paymentLinkType", "linkStatus", "tokenLinkStatus", "eventDate"]

    @field_validator('payment_link_type')
    def payment_link_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'PaymentLink', 'PaymentIntent', 'TokenLink', 'Invoice']):
            raise ValueError("must be one of enum values ('NA', 'PaymentLink', 'PaymentIntent', 'TokenLink', 'Invoice')")
        return value

    @field_validator('link_status')
    def link_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Created', 'Enabled', 'Disabled', 'Expired', 'Paid', 'PaymentInitiated', 'None']):
            raise ValueError("must be one of enum values ('Created', 'Enabled', 'Disabled', 'Expired', 'Paid', 'PaymentInitiated', 'None')")
        return value

    @field_validator('token_link_status')
    def token_link_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'Created', 'Completed', 'Expired', 'Invalidated', 'Failed']):
            raise ValueError("must be one of enum values ('NA', 'Created', 'Completed', 'Expired', 'Invalidated', 'Failed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SecureTokenLinkByIdResponseTimeLineInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SecureTokenLinkByIdResponseTimeLineInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "tokenLinkId": obj.get("tokenLinkId"),
            "merchantId": obj.get("merchantId"),
            "paymentLinkType": obj.get("paymentLinkType"),
            "linkStatus": obj.get("linkStatus"),
            "tokenLinkStatus": obj.get("tokenLinkStatus"),
            "eventDate": obj.get("eventDate")
        })
        return _obj


