# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SecureVendorResponseDTOPhysicalAddress(BaseModel):
    """
    SecureVendorResponseDTOPhysicalAddress
    """ # noqa: E501
    attention: Optional[StrictStr] = Field(default=None, description="Attention to (optional)")
    address_line1: Optional[StrictStr] = Field(default=None, description="Address line 1", alias="addressLine1")
    address_line2: Optional[StrictStr] = Field(default=None, description="Address line 2 (optional)", alias="addressLine2")
    city: Optional[StrictStr] = Field(default=None, description="City")
    state: Optional[StrictStr] = Field(default=None, description="State")
    country: Optional[StrictStr] = Field(default=None, description="Country")
    postal_code: Optional[StrictStr] = Field(default=None, description="Postal code", alias="postalCode")
    address_type: Optional[StrictStr] = Field(default=None, alias="addressType")
    address_source: Optional[StrictStr] = Field(default=None, alias="addressSource")
    vendor_status: Optional[StrictStr] = Field(default=None, alias="vendorStatus")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    modified_by: Optional[StrictStr] = Field(default=None, alias="modifiedBy")
    created_on: Optional[StrictStr] = Field(default=None, alias="createdOn")
    modified_on: Optional[StrictStr] = Field(default=None, alias="modifiedOn")
    approved_date: Optional[StrictStr] = Field(default=None, alias="approvedDate")
    ofac_verified: Optional[StrictStr] = Field(default=None, alias="ofacVerified")
    address_verified: Optional[StrictStr] = Field(default=None, alias="addressVerified")
    __properties: ClassVar[List[str]] = ["attention", "addressLine1", "addressLine2", "city", "state", "country", "postalCode", "addressType", "addressSource", "vendorStatus", "createdBy", "modifiedBy", "createdOn", "modifiedOn", "approvedDate", "ofacVerified", "addressVerified"]

    @field_validator('address_type')
    def address_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'Remittance', 'Correspondence', 'Physical']):
            raise ValueError("must be one of enum values ('NA', 'Remittance', 'Correspondence', 'Physical')")
        return value

    @field_validator('address_source')
    def address_source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA']):
            raise ValueError("must be one of enum values ('NA')")
        return value

    @field_validator('vendor_status')
    def vendor_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NA', 'InReview', 'Approved', 'Denied', 'Suspend', 'Deleted']):
            raise ValueError("must be one of enum values ('NA', 'InReview', 'Approved', 'Denied', 'Suspend', 'Deleted')")
        return value

    @field_validator('ofac_verified')
    def ofac_verified_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'Valid', 'Invalid']):
            raise ValueError("must be one of enum values ('None', 'Valid', 'Invalid')")
        return value

    @field_validator('address_verified')
    def address_verified_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'Valid', 'Invalid']):
            raise ValueError("must be one of enum values ('None', 'Valid', 'Invalid')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SecureVendorResponseDTOPhysicalAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SecureVendorResponseDTOPhysicalAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attention": obj.get("attention"),
            "addressLine1": obj.get("addressLine1"),
            "addressLine2": obj.get("addressLine2"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "country": obj.get("country"),
            "postalCode": obj.get("postalCode"),
            "addressType": obj.get("addressType"),
            "addressSource": obj.get("addressSource"),
            "vendorStatus": obj.get("vendorStatus"),
            "createdBy": obj.get("createdBy"),
            "modifiedBy": obj.get("modifiedBy"),
            "createdOn": obj.get("createdOn"),
            "modifiedOn": obj.get("modifiedOn"),
            "approvedDate": obj.get("approvedDate"),
            "ofacVerified": obj.get("ofacVerified"),
            "addressVerified": obj.get("addressVerified")
        })
        return _obj


