# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.payment_intent_request_pfr import PaymentIntentRequestPfr
from openapi_client.models.transaction_detail_response_splits_inner import TransactionDetailResponseSplitsInner
from openapi_client.models.transaction_detail_response_tender_info import TransactionDetailResponseTenderInfo
from openapi_client.models.transaction_payment_response_billing_contact import TransactionPaymentResponseBillingContact
from openapi_client.models.transaction_payment_response_refund_origin import TransactionPaymentResponseRefundOrigin
from openapi_client.models.transaction_payment_response_refund_transactions import TransactionPaymentResponseRefundTransactions
from openapi_client.models.transaction_payment_response_transaction_result import TransactionPaymentResponseTransactionResult
from typing import Optional, Set
from typing_extensions import Self

class TransactionDetailResponse(BaseModel):
    """
    TransactionDetailResponse
    """ # noqa: E501
    transaction_id: Optional[StrictStr] = Field(default=None, alias="transactionId")
    batch_id: Optional[StrictStr] = Field(default=None, alias="batchId")
    transaction_code: Optional[StrictStr] = Field(default=None, alias="transactionCode")
    transaction_origin: Optional[StrictStr] = Field(default=None, alias="transactionOrigin")
    refund_origin: Optional[TransactionPaymentResponseRefundOrigin] = Field(default=None, alias="refundOrigin")
    billing_contact: Optional[TransactionPaymentResponseBillingContact] = Field(default=None, alias="billingContact")
    reference_transaction_id: Optional[StrictStr] = Field(default=None, alias="referenceTransactionId")
    transaction_date: Optional[StrictStr] = Field(default=None, alias="transactionDate")
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    ip_address: Optional[StrictStr] = Field(default=None, alias="ipAddress")
    operation_type: Optional[StrictStr] = Field(default=None, alias="operationType")
    channel_type: Optional[StrictStr] = Field(default=None, alias="channelType")
    process_method: Optional[StrictStr] = Field(default=None, alias="processMethod")
    payment_type: Optional[StrictStr] = Field(default=None, alias="paymentType")
    payment_category: Optional[StrictStr] = Field(default=None, alias="paymentCategory")
    processor_name: Optional[StrictStr] = Field(default=None, alias="processorName")
    tender_info: Optional[TransactionDetailResponseTenderInfo] = Field(default=None, alias="tenderInfo")
    reference_customer_id: Optional[StrictStr] = Field(default=None, alias="referenceCustomerId")
    invoice_no: Optional[StrictStr] = Field(default=None, alias="invoiceNo")
    reference_no: Optional[StrictStr] = Field(default=None, alias="referenceNo")
    remarks: Optional[StrictStr] = None
    terminal_id: Optional[StrictStr] = Field(default=None, alias="terminalId")
    transaction_status: Optional[StrictStr] = Field(default=None, alias="transactionStatus")
    previous_transaction_status: Optional[StrictStr] = Field(default=None, alias="previousTransactionStatus")
    transaction_result: Optional[TransactionPaymentResponseTransactionResult] = Field(default=None, alias="transactionResult")
    invoice_id: Optional[StrictStr] = Field(default=None, alias="invoiceId")
    token_link_id: Optional[StrictStr] = Field(default=None, alias="tokenLinkId")
    payment_link_id: Optional[StrictStr] = Field(default=None, alias="paymentLinkId")
    additional_fields: Optional[StrictStr] = Field(default=None, alias="additionalFields")
    settlement_date: Optional[StrictStr] = Field(default=None, alias="settlementDate")
    issuer: Optional[StrictStr] = None
    merchant_name: Optional[StrictStr] = Field(default=None, alias="merchantName")
    merchant_dba_name: Optional[StrictStr] = Field(default=None, alias="merchantDBAName")
    splits: Optional[List[TransactionDetailResponseSplitsInner]] = None
    payment_description: Optional[StrictStr] = Field(default=None, alias="paymentDescription")
    refund_transactions: Optional[TransactionPaymentResponseRefundTransactions] = Field(default=None, alias="refundTransactions")
    total_refund_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalRefundAmount")
    remaining_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="remainingAmount")
    chargeback_reason: Optional[StrictStr] = Field(default=None, alias="chargebackReason")
    chargeback_reason_code: Optional[StrictStr] = Field(default=None, alias="chargebackReasonCode")
    chargeback_date_time: Optional[StrictStr] = Field(default=None, alias="chargebackDateTime")
    sub_total_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="subTotalAmount")
    company_name: Optional[StrictStr] = Field(default=None, alias="companyName")
    api_version: Optional[StrictStr] = Field(default=None, alias="apiVersion")
    charge_back_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="chargeBackAmount")
    suppress_technology_fee: Optional[StrictBool] = Field(default=None, alias="suppressTechnologyFee")
    is_premium_financier: Optional[StrictBool] = Field(default=None, alias="isPremiumFinancier")
    pfr: Optional[PaymentIntentRequestPfr] = None
    __properties: ClassVar[List[str]] = ["transactionId", "batchId", "transactionCode", "transactionOrigin", "refundOrigin", "billingContact", "referenceTransactionId", "transactionDate", "merchantId", "ipAddress", "operationType", "channelType", "processMethod", "paymentType", "paymentCategory", "processorName", "tenderInfo", "referenceCustomerId", "invoiceNo", "referenceNo", "remarks", "terminalId", "transactionStatus", "previousTransactionStatus", "transactionResult", "invoiceId", "tokenLinkId", "paymentLinkId", "additionalFields", "settlementDate", "issuer", "merchantName", "merchantDBAName", "splits", "paymentDescription", "refundTransactions", "totalRefundAmount", "remainingAmount", "chargebackReason", "chargebackReasonCode", "chargebackDateTime", "subTotalAmount", "companyName", "apiVersion", "chargeBackAmount", "suppressTechnologyFee", "isPremiumFinancier", "pfr"]

    @field_validator('transaction_origin')
    def transaction_origin_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Terminal', 'VirtualTerminal', 'WebForm', 'API', 'Schedule', 'Batch', 'PaymentIntent']):
            raise ValueError("must be one of enum values ('Terminal', 'VirtualTerminal', 'WebForm', 'API', 'Schedule', 'Batch', 'PaymentIntent')")
        return value

    @field_validator('operation_type')
    def operation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Sale', 'VerifyOnly', 'ForceSale', 'Adjust', 'Activate', 'Deactivate', 'Reload', 'Refund', 'Inquire', 'ReverseAuth']):
            raise ValueError("must be one of enum values ('Sale', 'VerifyOnly', 'ForceSale', 'Adjust', 'Activate', 'Deactivate', 'Reload', 'Refund', 'Inquire', 'ReverseAuth')")
        return value

    @field_validator('channel_type')
    def channel_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NotDefined', 'ACH', 'CreditCard', 'DebitCard']):
            raise ValueError("must be one of enum values ('NotDefined', 'ACH', 'CreditCard', 'DebitCard')")
        return value

    @field_validator('process_method')
    def process_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NotDefined', 'ACH', 'CardNotPresent']):
            raise ValueError("must be one of enum values ('NotDefined', 'ACH', 'CardNotPresent')")
        return value

    @field_validator('payment_type')
    def payment_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'AnytimePayment', 'SubDomain', 'PaymentIntent', 'PaymentLink', 'OpenPayment', 'TokenLink']):
            raise ValueError("must be one of enum values ('None', 'AnytimePayment', 'SubDomain', 'PaymentIntent', 'PaymentLink', 'OpenPayment', 'TokenLink')")
        return value

    @field_validator('payment_category')
    def payment_category_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'MerchantPayment', 'MPIPD', 'MPIPI', 'PFD', 'PFI']):
            raise ValueError("must be one of enum values ('None', 'MerchantPayment', 'MPIPD', 'MPIPI', 'PFD', 'PFI')")
        return value

    @field_validator('transaction_status')
    def transaction_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'ChargebackReversed', 'RefundedReversed', 'Paid', 'PaidChargeback', 'PaidChargebackReversed', 'PaidRefunded', 'PaidRefundedReversed', 'None', 'Unknown']):
            raise ValueError("must be one of enum values ('Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'ChargebackReversed', 'RefundedReversed', 'Paid', 'PaidChargeback', 'PaidChargebackReversed', 'PaidRefunded', 'PaidRefundedReversed', 'None', 'Unknown')")
        return value

    @field_validator('previous_transaction_status')
    def previous_transaction_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'ChargebackReversed', 'RefundedReversed', 'Paid', 'PaidChargeback', 'PaidChargebackReversed', 'PaidRefunded', 'PaidRefundedReversed', 'None', 'Unknown']):
            raise ValueError("must be one of enum values ('Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'ChargebackReversed', 'RefundedReversed', 'Paid', 'PaidChargeback', 'PaidChargebackReversed', 'PaidRefunded', 'PaidRefundedReversed', 'None', 'Unknown')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionDetailResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of refund_origin
        if self.refund_origin:
            _dict['refundOrigin'] = self.refund_origin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of billing_contact
        if self.billing_contact:
            _dict['billingContact'] = self.billing_contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tender_info
        if self.tender_info:
            _dict['tenderInfo'] = self.tender_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transaction_result
        if self.transaction_result:
            _dict['transactionResult'] = self.transaction_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in splits (list)
        _items = []
        if self.splits:
            for _item_splits in self.splits:
                if _item_splits:
                    _items.append(_item_splits.to_dict())
            _dict['splits'] = _items
        # override the default output from pydantic by calling `to_dict()` of refund_transactions
        if self.refund_transactions:
            _dict['refundTransactions'] = self.refund_transactions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pfr
        if self.pfr:
            _dict['pfr'] = self.pfr.to_dict()
        # set to None if payment_link_id (nullable) is None
        # and model_fields_set contains the field
        if self.payment_link_id is None and "payment_link_id" in self.model_fields_set:
            _dict['paymentLinkId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionDetailResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transactionId": obj.get("transactionId"),
            "batchId": obj.get("batchId"),
            "transactionCode": obj.get("transactionCode"),
            "transactionOrigin": obj.get("transactionOrigin"),
            "refundOrigin": TransactionPaymentResponseRefundOrigin.from_dict(obj["refundOrigin"]) if obj.get("refundOrigin") is not None else None,
            "billingContact": TransactionPaymentResponseBillingContact.from_dict(obj["billingContact"]) if obj.get("billingContact") is not None else None,
            "referenceTransactionId": obj.get("referenceTransactionId"),
            "transactionDate": obj.get("transactionDate"),
            "merchantId": obj.get("merchantId"),
            "ipAddress": obj.get("ipAddress"),
            "operationType": obj.get("operationType"),
            "channelType": obj.get("channelType"),
            "processMethod": obj.get("processMethod"),
            "paymentType": obj.get("paymentType"),
            "paymentCategory": obj.get("paymentCategory"),
            "processorName": obj.get("processorName"),
            "tenderInfo": TransactionDetailResponseTenderInfo.from_dict(obj["tenderInfo"]) if obj.get("tenderInfo") is not None else None,
            "referenceCustomerId": obj.get("referenceCustomerId"),
            "invoiceNo": obj.get("invoiceNo"),
            "referenceNo": obj.get("referenceNo"),
            "remarks": obj.get("remarks"),
            "terminalId": obj.get("terminalId"),
            "transactionStatus": obj.get("transactionStatus"),
            "previousTransactionStatus": obj.get("previousTransactionStatus"),
            "transactionResult": TransactionPaymentResponseTransactionResult.from_dict(obj["transactionResult"]) if obj.get("transactionResult") is not None else None,
            "invoiceId": obj.get("invoiceId"),
            "tokenLinkId": obj.get("tokenLinkId"),
            "paymentLinkId": obj.get("paymentLinkId"),
            "additionalFields": obj.get("additionalFields"),
            "settlementDate": obj.get("settlementDate"),
            "issuer": obj.get("issuer"),
            "merchantName": obj.get("merchantName"),
            "merchantDBAName": obj.get("merchantDBAName"),
            "splits": [TransactionDetailResponseSplitsInner.from_dict(_item) for _item in obj["splits"]] if obj.get("splits") is not None else None,
            "paymentDescription": obj.get("paymentDescription"),
            "refundTransactions": TransactionPaymentResponseRefundTransactions.from_dict(obj["refundTransactions"]) if obj.get("refundTransactions") is not None else None,
            "totalRefundAmount": obj.get("totalRefundAmount"),
            "remainingAmount": obj.get("remainingAmount"),
            "chargebackReason": obj.get("chargebackReason"),
            "chargebackReasonCode": obj.get("chargebackReasonCode"),
            "chargebackDateTime": obj.get("chargebackDateTime"),
            "subTotalAmount": obj.get("subTotalAmount"),
            "companyName": obj.get("companyName"),
            "apiVersion": obj.get("apiVersion"),
            "chargeBackAmount": obj.get("chargeBackAmount"),
            "suppressTechnologyFee": obj.get("suppressTechnologyFee"),
            "isPremiumFinancier": obj.get("isPremiumFinancier"),
            "pfr": PaymentIntentRequestPfr.from_dict(obj["pfr"]) if obj.get("pfr") is not None else None
        })
        return _obj


