# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.transaction_payment_response_ach_tender_info import TransactionPaymentResponseAchTenderInfo
from openapi_client.models.transaction_payment_response_billing_contact import TransactionPaymentResponseBillingContact
from openapi_client.models.transaction_payment_response_cc_tender_info import TransactionPaymentResponseCcTenderInfo
from openapi_client.models.transaction_payment_response_refund_origin import TransactionPaymentResponseRefundOrigin
from openapi_client.models.transaction_payment_response_refund_transactions import TransactionPaymentResponseRefundTransactions
from openapi_client.models.transaction_payment_response_transaction_entity_split_responses_inner import TransactionPaymentResponseTransactionEntitySplitResponsesInner
from openapi_client.models.transaction_payment_response_transaction_result import TransactionPaymentResponseTransactionResult
from typing import Optional, Set
from typing_extensions import Self

class TransactionPaymentResponse(BaseModel):
    """
    TransactionPaymentResponse
    """ # noqa: E501
    transaction_id: Optional[StrictStr] = Field(default=None, alias="transactionId")
    transaction_code: Optional[StrictStr] = Field(default=None, alias="transactionCode")
    billing_contact: Optional[TransactionPaymentResponseBillingContact] = Field(default=None, alias="billingContact")
    transaction_date: Optional[StrictStr] = Field(default=None, alias="transactionDate")
    merchant_id: Optional[StrictStr] = Field(default=None, alias="merchantId")
    ip_address: Optional[StrictStr] = Field(default=None, alias="ipAddress")
    channel_type: Optional[StrictStr] = Field(default=None, alias="channelType")
    process_method: Optional[StrictStr] = Field(default=None, alias="processMethod")
    processor_name: Optional[StrictStr] = Field(default=None, alias="processorName")
    transaction_origin: Optional[StrictStr] = Field(default=None, alias="transactionOrigin")
    refund_origin: Optional[TransactionPaymentResponseRefundOrigin] = Field(default=None, alias="refundOrigin")
    ach_tender_info: Optional[TransactionPaymentResponseAchTenderInfo] = Field(default=None, alias="achTenderInfo")
    cc_tender_info: Optional[TransactionPaymentResponseCcTenderInfo] = Field(default=None, alias="ccTenderInfo")
    debit_card_tender_info: Optional[TransactionPaymentResponseCcTenderInfo] = Field(default=None, alias="debitCardTenderInfo")
    reference_customer_id: Optional[StrictStr] = Field(default=None, alias="referenceCustomerId")
    invoice_no: Optional[StrictStr] = Field(default=None, alias="invoiceNo")
    reference_no: Optional[StrictStr] = Field(default=None, alias="referenceNo")
    remarks: Optional[StrictStr] = None
    terminal_id: Optional[StrictStr] = Field(default=None, alias="terminalId")
    transaction_status: Optional[StrictStr] = Field(default=None, alias="transactionStatus")
    transaction_result: Optional[TransactionPaymentResponseTransactionResult] = Field(default=None, alias="transactionResult")
    invoice_id: Optional[StrictStr] = Field(default=None, alias="invoiceId")
    payment_link_id: Optional[StrictStr] = Field(default=None, alias="paymentLinkId")
    additional_fields: Optional[StrictStr] = Field(default=None, alias="additionalFields")
    settlement_date: Optional[StrictStr] = Field(default=None, alias="settlementDate")
    issuer: Optional[StrictStr] = None
    payment_type: Optional[StrictStr] = Field(default=None, alias="paymentType")
    payment_category: Optional[StrictStr] = Field(default=None, alias="paymentCategory")
    transaction_entity_split_responses: Optional[List[TransactionPaymentResponseTransactionEntitySplitResponsesInner]] = Field(default=None, alias="transactionEntitySplitResponses")
    payment_description: Optional[StrictStr] = Field(default=None, alias="paymentDescription")
    refund_transactions: Optional[TransactionPaymentResponseRefundTransactions] = Field(default=None, alias="refundTransactions")
    chargeback_target_account: Optional[StrictStr] = Field(default=None, alias="chargebackTargetAccount")
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    user_name: Optional[StrictStr] = Field(default=None, alias="userName")
    charge_back_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="chargeBackAmount")
    suppress_technology_fee: Optional[StrictBool] = Field(default=None, alias="suppressTechnologyFee")
    __properties: ClassVar[List[str]] = ["transactionId", "transactionCode", "billingContact", "transactionDate", "merchantId", "ipAddress", "channelType", "processMethod", "processorName", "transactionOrigin", "refundOrigin", "achTenderInfo", "ccTenderInfo", "debitCardTenderInfo", "referenceCustomerId", "invoiceNo", "referenceNo", "remarks", "terminalId", "transactionStatus", "transactionResult", "invoiceId", "paymentLinkId", "additionalFields", "settlementDate", "issuer", "paymentType", "paymentCategory", "transactionEntitySplitResponses", "paymentDescription", "refundTransactions", "chargebackTargetAccount", "userId", "userName", "chargeBackAmount", "suppressTechnologyFee"]

    @field_validator('channel_type')
    def channel_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NotDefined', 'ACH', 'CreditCard', 'DebitCard']):
            raise ValueError("must be one of enum values ('NotDefined', 'ACH', 'CreditCard', 'DebitCard')")
        return value

    @field_validator('process_method')
    def process_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACH', 'CardNotPresent']):
            raise ValueError("must be one of enum values ('ACH', 'CardNotPresent')")
        return value

    @field_validator('transaction_origin')
    def transaction_origin_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['WebForm', 'PaymentIntent']):
            raise ValueError("must be one of enum values ('WebForm', 'PaymentIntent')")
        return value

    @field_validator('transaction_status')
    def transaction_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'None', 'Unknown']):
            raise ValueError("must be one of enum values ('Created', 'PendingForAuthorized', 'Authorized', 'Posted', 'Captured', 'Failed', 'Returned', 'Chargeback', 'Cancelled', 'Refunded', 'Approved', 'CancelAttempt', 'RefundAttempt', 'Hold', 'Denied', 'SettlementHold', 'Success', 'Retried', 'ReprocessAttempt', 'Reprocessed', 'None', 'Unknown')")
        return value

    @field_validator('payment_type')
    def payment_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'AnytimePayment', 'SubDomain', 'PaymentIntent', 'PaymentLink', 'OpenPayment', 'TokenLink']):
            raise ValueError("must be one of enum values ('None', 'AnytimePayment', 'SubDomain', 'PaymentIntent', 'PaymentLink', 'OpenPayment', 'TokenLink')")
        return value

    @field_validator('payment_category')
    def payment_category_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'MerchantPayment', 'MPIPD', 'MPIPI', 'PFD', 'PFI']):
            raise ValueError("must be one of enum values ('None', 'MerchantPayment', 'MPIPD', 'MPIPI', 'PFD', 'PFI')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionPaymentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of billing_contact
        if self.billing_contact:
            _dict['billingContact'] = self.billing_contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of refund_origin
        if self.refund_origin:
            _dict['refundOrigin'] = self.refund_origin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ach_tender_info
        if self.ach_tender_info:
            _dict['achTenderInfo'] = self.ach_tender_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cc_tender_info
        if self.cc_tender_info:
            _dict['ccTenderInfo'] = self.cc_tender_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of debit_card_tender_info
        if self.debit_card_tender_info:
            _dict['debitCardTenderInfo'] = self.debit_card_tender_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transaction_result
        if self.transaction_result:
            _dict['transactionResult'] = self.transaction_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in transaction_entity_split_responses (list)
        _items = []
        if self.transaction_entity_split_responses:
            for _item_transaction_entity_split_responses in self.transaction_entity_split_responses:
                if _item_transaction_entity_split_responses:
                    _items.append(_item_transaction_entity_split_responses.to_dict())
            _dict['transactionEntitySplitResponses'] = _items
        # override the default output from pydantic by calling `to_dict()` of refund_transactions
        if self.refund_transactions:
            _dict['refundTransactions'] = self.refund_transactions.to_dict()
        # set to None if charge_back_amount (nullable) is None
        # and model_fields_set contains the field
        if self.charge_back_amount is None and "charge_back_amount" in self.model_fields_set:
            _dict['chargeBackAmount'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionPaymentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transactionId": obj.get("transactionId"),
            "transactionCode": obj.get("transactionCode"),
            "billingContact": TransactionPaymentResponseBillingContact.from_dict(obj["billingContact"]) if obj.get("billingContact") is not None else None,
            "transactionDate": obj.get("transactionDate"),
            "merchantId": obj.get("merchantId"),
            "ipAddress": obj.get("ipAddress"),
            "channelType": obj.get("channelType"),
            "processMethod": obj.get("processMethod"),
            "processorName": obj.get("processorName"),
            "transactionOrigin": obj.get("transactionOrigin"),
            "refundOrigin": TransactionPaymentResponseRefundOrigin.from_dict(obj["refundOrigin"]) if obj.get("refundOrigin") is not None else None,
            "achTenderInfo": TransactionPaymentResponseAchTenderInfo.from_dict(obj["achTenderInfo"]) if obj.get("achTenderInfo") is not None else None,
            "ccTenderInfo": TransactionPaymentResponseCcTenderInfo.from_dict(obj["ccTenderInfo"]) if obj.get("ccTenderInfo") is not None else None,
            "debitCardTenderInfo": TransactionPaymentResponseCcTenderInfo.from_dict(obj["debitCardTenderInfo"]) if obj.get("debitCardTenderInfo") is not None else None,
            "referenceCustomerId": obj.get("referenceCustomerId"),
            "invoiceNo": obj.get("invoiceNo"),
            "referenceNo": obj.get("referenceNo"),
            "remarks": obj.get("remarks"),
            "terminalId": obj.get("terminalId"),
            "transactionStatus": obj.get("transactionStatus"),
            "transactionResult": TransactionPaymentResponseTransactionResult.from_dict(obj["transactionResult"]) if obj.get("transactionResult") is not None else None,
            "invoiceId": obj.get("invoiceId"),
            "paymentLinkId": obj.get("paymentLinkId"),
            "additionalFields": obj.get("additionalFields"),
            "settlementDate": obj.get("settlementDate"),
            "issuer": obj.get("issuer"),
            "paymentType": obj.get("paymentType"),
            "paymentCategory": obj.get("paymentCategory"),
            "transactionEntitySplitResponses": [TransactionPaymentResponseTransactionEntitySplitResponsesInner.from_dict(_item) for _item in obj["transactionEntitySplitResponses"]] if obj.get("transactionEntitySplitResponses") is not None else None,
            "paymentDescription": obj.get("paymentDescription"),
            "refundTransactions": TransactionPaymentResponseRefundTransactions.from_dict(obj["refundTransactions"]) if obj.get("refundTransactions") is not None else None,
            "chargebackTargetAccount": obj.get("chargebackTargetAccount"),
            "userId": obj.get("userId"),
            "userName": obj.get("userName"),
            "chargeBackAmount": obj.get("chargeBackAmount"),
            "suppressTechnologyFee": obj.get("suppressTechnologyFee")
        })
        return _obj


