# coding: utf-8

"""
    Secure API

    Secure API

    The version of the OpenAPI document: 2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.transaction_payment_response_ach_tender_info_commission_type import TransactionPaymentResponseAchTenderInfoCommissionType
from typing import Optional, Set
from typing_extensions import Self

class TransactionPaymentResponseCcTenderInfo(BaseModel):
    """
    TransactionPaymentResponseCcTenderInfo
    """ # noqa: E501
    card_holder_name: Optional[StrictStr] = Field(default=None, alias="cardHolderName")
    card_type: Optional[StrictStr] = Field(default=None, alias="cardType")
    mask_card_number: Optional[StrictStr] = Field(default=None, alias="maskCardNumber")
    card_expiry: Optional[StrictStr] = Field(default=None, alias="cardExpiry")
    capture_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="captureAmount")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    convenience_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="convenienceAmount")
    bin_number: Optional[StrictStr] = Field(default=None, alias="binNumber")
    adjustment_percent_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="adjustmentPercentValue")
    adjustment_fixed_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="adjustmentFixedValue")
    adjustment_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="adjustmentAmount")
    adjustment_display_name: Optional[StrictStr] = Field(default=None, alias="adjustmentDisplayName")
    adjustment_descriptor_message: Optional[StrictStr] = Field(default=None, alias="adjustmentDescriptorMessage")
    payment_adjustment_type: Optional[StrictStr] = Field(default=None, alias="paymentAdjustmentType")
    pre_auth_code: Optional[StrictStr] = Field(default=None, alias="preAuthCode")
    mask_account: Optional[StrictStr] = Field(default=None, alias="maskAccount")
    account_token: Optional[StrictStr] = Field(default=None, alias="accountToken")
    account_token_message: Optional[StrictStr] = Field(default=None, alias="accountTokenMessage")
    create_account_token: Optional[StrictBool] = Field(default=None, alias="createAccountToken")
    commission_type: Optional[TransactionPaymentResponseAchTenderInfoCommissionType] = Field(default=None, alias="commissionType")
    commission_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="commissionValue")
    commission_fixed_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="commissionFixedValue")
    __properties: ClassVar[List[str]] = ["cardHolderName", "cardType", "maskCardNumber", "cardExpiry", "captureAmount", "amount", "convenienceAmount", "binNumber", "adjustmentPercentValue", "adjustmentFixedValue", "adjustmentAmount", "adjustmentDisplayName", "adjustmentDescriptorMessage", "paymentAdjustmentType", "preAuthCode", "maskAccount", "accountToken", "accountTokenMessage", "createAccountToken", "commissionType", "commissionValue", "commissionFixedValue"]

    @field_validator('payment_adjustment_type')
    def payment_adjustment_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'CashIncentive', 'Surcharge', 'ConvenienceFee', 'CashDiscount']):
            raise ValueError("must be one of enum values ('None', 'CashIncentive', 'Surcharge', 'ConvenienceFee', 'CashDiscount')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionPaymentResponseCcTenderInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of commission_type
        if self.commission_type:
            _dict['commissionType'] = self.commission_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionPaymentResponseCcTenderInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cardHolderName": obj.get("cardHolderName"),
            "cardType": obj.get("cardType"),
            "maskCardNumber": obj.get("maskCardNumber"),
            "cardExpiry": obj.get("cardExpiry"),
            "captureAmount": obj.get("captureAmount"),
            "amount": obj.get("amount"),
            "convenienceAmount": obj.get("convenienceAmount"),
            "binNumber": obj.get("binNumber"),
            "adjustmentPercentValue": obj.get("adjustmentPercentValue"),
            "adjustmentFixedValue": obj.get("adjustmentFixedValue"),
            "adjustmentAmount": obj.get("adjustmentAmount"),
            "adjustmentDisplayName": obj.get("adjustmentDisplayName"),
            "adjustmentDescriptorMessage": obj.get("adjustmentDescriptorMessage"),
            "paymentAdjustmentType": obj.get("paymentAdjustmentType"),
            "preAuthCode": obj.get("preAuthCode"),
            "maskAccount": obj.get("maskAccount"),
            "accountToken": obj.get("accountToken"),
            "accountTokenMessage": obj.get("accountTokenMessage"),
            "createAccountToken": obj.get("createAccountToken"),
            "commissionType": TransactionPaymentResponseAchTenderInfoCommissionType.from_dict(obj["commissionType"]) if obj.get("commissionType") is not None else None,
            "commissionValue": obj.get("commissionValue"),
            "commissionFixedValue": obj.get("commissionFixedValue")
        })
        return _obj


